// Code generated by ent, DO NOT EDIT.

package portmapping

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ca-x/tailcat-webui/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldUserID, v))
}

// ServerID applies equality check predicate on the "server_id" field. It's identical to ServerIDEQ.
func ServerID(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldServerID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldName, v))
}

// ListenPort applies equality check predicate on the "listen_port" field. It's identical to ListenPortEQ.
func ListenPort(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldListenPort, v))
}

// TargetHost applies equality check predicate on the "target_host" field. It's identical to TargetHostEQ.
func TargetHost(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldTargetHost, v))
}

// TargetPort applies equality check predicate on the "target_port" field. It's identical to TargetPortEQ.
func TargetPort(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldTargetPort, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldContainsFold(FieldUserID, v))
}

// ServerIDEQ applies the EQ predicate on the "server_id" field.
func ServerIDEQ(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldServerID, v))
}

// ServerIDNEQ applies the NEQ predicate on the "server_id" field.
func ServerIDNEQ(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNEQ(FieldServerID, v))
}

// ServerIDIn applies the In predicate on the "server_id" field.
func ServerIDIn(vs ...string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldIn(FieldServerID, vs...))
}

// ServerIDNotIn applies the NotIn predicate on the "server_id" field.
func ServerIDNotIn(vs ...string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNotIn(FieldServerID, vs...))
}

// ServerIDGT applies the GT predicate on the "server_id" field.
func ServerIDGT(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGT(FieldServerID, v))
}

// ServerIDGTE applies the GTE predicate on the "server_id" field.
func ServerIDGTE(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGTE(FieldServerID, v))
}

// ServerIDLT applies the LT predicate on the "server_id" field.
func ServerIDLT(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLT(FieldServerID, v))
}

// ServerIDLTE applies the LTE predicate on the "server_id" field.
func ServerIDLTE(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLTE(FieldServerID, v))
}

// ServerIDContains applies the Contains predicate on the "server_id" field.
func ServerIDContains(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldContains(FieldServerID, v))
}

// ServerIDHasPrefix applies the HasPrefix predicate on the "server_id" field.
func ServerIDHasPrefix(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldHasPrefix(FieldServerID, v))
}

// ServerIDHasSuffix applies the HasSuffix predicate on the "server_id" field.
func ServerIDHasSuffix(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldHasSuffix(FieldServerID, v))
}

// ServerIDEqualFold applies the EqualFold predicate on the "server_id" field.
func ServerIDEqualFold(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEqualFold(FieldServerID, v))
}

// ServerIDContainsFold applies the ContainsFold predicate on the "server_id" field.
func ServerIDContainsFold(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldContainsFold(FieldServerID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldContainsFold(FieldName, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNotIn(FieldKind, vs...))
}

// ListenPortEQ applies the EQ predicate on the "listen_port" field.
func ListenPortEQ(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldListenPort, v))
}

// ListenPortNEQ applies the NEQ predicate on the "listen_port" field.
func ListenPortNEQ(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNEQ(FieldListenPort, v))
}

// ListenPortIn applies the In predicate on the "listen_port" field.
func ListenPortIn(vs ...uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldIn(FieldListenPort, vs...))
}

// ListenPortNotIn applies the NotIn predicate on the "listen_port" field.
func ListenPortNotIn(vs ...uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNotIn(FieldListenPort, vs...))
}

// ListenPortGT applies the GT predicate on the "listen_port" field.
func ListenPortGT(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGT(FieldListenPort, v))
}

// ListenPortGTE applies the GTE predicate on the "listen_port" field.
func ListenPortGTE(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGTE(FieldListenPort, v))
}

// ListenPortLT applies the LT predicate on the "listen_port" field.
func ListenPortLT(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLT(FieldListenPort, v))
}

// ListenPortLTE applies the LTE predicate on the "listen_port" field.
func ListenPortLTE(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLTE(FieldListenPort, v))
}

// TargetHostEQ applies the EQ predicate on the "target_host" field.
func TargetHostEQ(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldTargetHost, v))
}

// TargetHostNEQ applies the NEQ predicate on the "target_host" field.
func TargetHostNEQ(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNEQ(FieldTargetHost, v))
}

// TargetHostIn applies the In predicate on the "target_host" field.
func TargetHostIn(vs ...string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldIn(FieldTargetHost, vs...))
}

// TargetHostNotIn applies the NotIn predicate on the "target_host" field.
func TargetHostNotIn(vs ...string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNotIn(FieldTargetHost, vs...))
}

// TargetHostGT applies the GT predicate on the "target_host" field.
func TargetHostGT(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGT(FieldTargetHost, v))
}

// TargetHostGTE applies the GTE predicate on the "target_host" field.
func TargetHostGTE(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGTE(FieldTargetHost, v))
}

// TargetHostLT applies the LT predicate on the "target_host" field.
func TargetHostLT(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLT(FieldTargetHost, v))
}

// TargetHostLTE applies the LTE predicate on the "target_host" field.
func TargetHostLTE(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLTE(FieldTargetHost, v))
}

// TargetHostContains applies the Contains predicate on the "target_host" field.
func TargetHostContains(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldContains(FieldTargetHost, v))
}

// TargetHostHasPrefix applies the HasPrefix predicate on the "target_host" field.
func TargetHostHasPrefix(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldHasPrefix(FieldTargetHost, v))
}

// TargetHostHasSuffix applies the HasSuffix predicate on the "target_host" field.
func TargetHostHasSuffix(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldHasSuffix(FieldTargetHost, v))
}

// TargetHostEqualFold applies the EqualFold predicate on the "target_host" field.
func TargetHostEqualFold(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEqualFold(FieldTargetHost, v))
}

// TargetHostContainsFold applies the ContainsFold predicate on the "target_host" field.
func TargetHostContainsFold(v string) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldContainsFold(FieldTargetHost, v))
}

// TargetPortEQ applies the EQ predicate on the "target_port" field.
func TargetPortEQ(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldTargetPort, v))
}

// TargetPortNEQ applies the NEQ predicate on the "target_port" field.
func TargetPortNEQ(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNEQ(FieldTargetPort, v))
}

// TargetPortIn applies the In predicate on the "target_port" field.
func TargetPortIn(vs ...uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldIn(FieldTargetPort, vs...))
}

// TargetPortNotIn applies the NotIn predicate on the "target_port" field.
func TargetPortNotIn(vs ...uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNotIn(FieldTargetPort, vs...))
}

// TargetPortGT applies the GT predicate on the "target_port" field.
func TargetPortGT(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGT(FieldTargetPort, v))
}

// TargetPortGTE applies the GTE predicate on the "target_port" field.
func TargetPortGTE(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGTE(FieldTargetPort, v))
}

// TargetPortLT applies the LT predicate on the "target_port" field.
func TargetPortLT(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLT(FieldTargetPort, v))
}

// TargetPortLTE applies the LTE predicate on the "target_port" field.
func TargetPortLTE(v uint16) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLTE(FieldTargetPort, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PortMapping {
	return predicate.PortMapping(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasServer applies the HasEdge predicate on the "server" edge.
func HasServer() predicate.PortMapping {
	return predicate.PortMapping(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServerTable, ServerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServerWith applies the HasEdge predicate on the "server" edge with a given conditions (other predicates).
func HasServerWith(preds ...predicate.TailServer) predicate.PortMapping {
	return predicate.PortMapping(func(s *sql.Selector) {
		step := newServerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PortMapping) predicate.PortMapping {
	return predicate.PortMapping(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PortMapping) predicate.PortMapping {
	return predicate.PortMapping(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PortMapping) predicate.PortMapping {
	return predicate.PortMapping(sql.NotPredicates(p))
}
