// Code generated by ent, DO NOT EDIT.

package loginflow

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the loginflow type in the database.
	Label = "login_flow"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStateHash holds the string denoting the state_hash field in the database.
	FieldStateHash = "state_hash"
	// FieldNonce holds the string denoting the nonce field in the database.
	FieldNonce = "nonce"
	// FieldCodeVerifier holds the string denoting the code_verifier field in the database.
	FieldCodeVerifier = "code_verifier"
	// FieldReturnTo holds the string denoting the return_to field in the database.
	FieldReturnTo = "return_to"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the loginflow in the database.
	Table = "login_flows"
)

// Columns holds all SQL columns for loginflow fields.
var Columns = []string{
	FieldID,
	FieldStateHash,
	FieldNonce,
	FieldCodeVerifier,
	FieldReturnTo,
	FieldExpiresAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultReturnTo holds the default value on creation for the "return_to" field.
	DefaultReturnTo string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the LoginFlow queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStateHash orders the results by the state_hash field.
func ByStateHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStateHash, opts...).ToFunc()
}

// ByNonce orders the results by the nonce field.
func ByNonce(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNonce, opts...).ToFunc()
}

// ByCodeVerifier orders the results by the code_verifier field.
func ByCodeVerifier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeVerifier, opts...).ToFunc()
}

// ByReturnTo orders the results by the return_to field.
func ByReturnTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReturnTo, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
