// Code generated by ent, DO NOT EDIT.

package sharefile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ca-x/tailcat-webui/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldUserID, v))
}

// ShareID applies equality check predicate on the "share_id" field. It's identical to ShareIDEQ.
func ShareID(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldShareID, v))
}

// StorageName applies equality check predicate on the "storage_name" field. It's identical to StorageNameEQ.
func StorageName(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldStorageName, v))
}

// VirtualPath applies equality check predicate on the "virtual_path" field. It's identical to VirtualPathEQ.
func VirtualPath(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldVirtualPath, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldSizeBytes, v))
}

// Mtime applies equality check predicate on the "mtime" field. It's identical to MtimeEQ.
func Mtime(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldMtime, v))
}

// Blake3 applies equality check predicate on the "blake3" field. It's identical to Blake3EQ.
func Blake3(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldBlake3, v))
}

// BlockSize applies equality check predicate on the "block_size" field. It's identical to BlockSizeEQ.
func BlockSize(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldBlockSize, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldContainsFold(FieldUserID, v))
}

// ShareIDEQ applies the EQ predicate on the "share_id" field.
func ShareIDEQ(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldShareID, v))
}

// ShareIDNEQ applies the NEQ predicate on the "share_id" field.
func ShareIDNEQ(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNEQ(FieldShareID, v))
}

// ShareIDIn applies the In predicate on the "share_id" field.
func ShareIDIn(vs ...string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldIn(FieldShareID, vs...))
}

// ShareIDNotIn applies the NotIn predicate on the "share_id" field.
func ShareIDNotIn(vs ...string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNotIn(FieldShareID, vs...))
}

// ShareIDGT applies the GT predicate on the "share_id" field.
func ShareIDGT(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGT(FieldShareID, v))
}

// ShareIDGTE applies the GTE predicate on the "share_id" field.
func ShareIDGTE(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGTE(FieldShareID, v))
}

// ShareIDLT applies the LT predicate on the "share_id" field.
func ShareIDLT(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLT(FieldShareID, v))
}

// ShareIDLTE applies the LTE predicate on the "share_id" field.
func ShareIDLTE(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLTE(FieldShareID, v))
}

// ShareIDContains applies the Contains predicate on the "share_id" field.
func ShareIDContains(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldContains(FieldShareID, v))
}

// ShareIDHasPrefix applies the HasPrefix predicate on the "share_id" field.
func ShareIDHasPrefix(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldHasPrefix(FieldShareID, v))
}

// ShareIDHasSuffix applies the HasSuffix predicate on the "share_id" field.
func ShareIDHasSuffix(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldHasSuffix(FieldShareID, v))
}

// ShareIDEqualFold applies the EqualFold predicate on the "share_id" field.
func ShareIDEqualFold(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEqualFold(FieldShareID, v))
}

// ShareIDContainsFold applies the ContainsFold predicate on the "share_id" field.
func ShareIDContainsFold(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldContainsFold(FieldShareID, v))
}

// StorageNameEQ applies the EQ predicate on the "storage_name" field.
func StorageNameEQ(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldStorageName, v))
}

// StorageNameNEQ applies the NEQ predicate on the "storage_name" field.
func StorageNameNEQ(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNEQ(FieldStorageName, v))
}

// StorageNameIn applies the In predicate on the "storage_name" field.
func StorageNameIn(vs ...string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldIn(FieldStorageName, vs...))
}

// StorageNameNotIn applies the NotIn predicate on the "storage_name" field.
func StorageNameNotIn(vs ...string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNotIn(FieldStorageName, vs...))
}

// StorageNameGT applies the GT predicate on the "storage_name" field.
func StorageNameGT(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGT(FieldStorageName, v))
}

// StorageNameGTE applies the GTE predicate on the "storage_name" field.
func StorageNameGTE(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGTE(FieldStorageName, v))
}

// StorageNameLT applies the LT predicate on the "storage_name" field.
func StorageNameLT(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLT(FieldStorageName, v))
}

// StorageNameLTE applies the LTE predicate on the "storage_name" field.
func StorageNameLTE(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLTE(FieldStorageName, v))
}

// StorageNameContains applies the Contains predicate on the "storage_name" field.
func StorageNameContains(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldContains(FieldStorageName, v))
}

// StorageNameHasPrefix applies the HasPrefix predicate on the "storage_name" field.
func StorageNameHasPrefix(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldHasPrefix(FieldStorageName, v))
}

// StorageNameHasSuffix applies the HasSuffix predicate on the "storage_name" field.
func StorageNameHasSuffix(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldHasSuffix(FieldStorageName, v))
}

// StorageNameEqualFold applies the EqualFold predicate on the "storage_name" field.
func StorageNameEqualFold(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEqualFold(FieldStorageName, v))
}

// StorageNameContainsFold applies the ContainsFold predicate on the "storage_name" field.
func StorageNameContainsFold(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldContainsFold(FieldStorageName, v))
}

// VirtualPathEQ applies the EQ predicate on the "virtual_path" field.
func VirtualPathEQ(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldVirtualPath, v))
}

// VirtualPathNEQ applies the NEQ predicate on the "virtual_path" field.
func VirtualPathNEQ(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNEQ(FieldVirtualPath, v))
}

// VirtualPathIn applies the In predicate on the "virtual_path" field.
func VirtualPathIn(vs ...string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldIn(FieldVirtualPath, vs...))
}

// VirtualPathNotIn applies the NotIn predicate on the "virtual_path" field.
func VirtualPathNotIn(vs ...string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNotIn(FieldVirtualPath, vs...))
}

// VirtualPathGT applies the GT predicate on the "virtual_path" field.
func VirtualPathGT(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGT(FieldVirtualPath, v))
}

// VirtualPathGTE applies the GTE predicate on the "virtual_path" field.
func VirtualPathGTE(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGTE(FieldVirtualPath, v))
}

// VirtualPathLT applies the LT predicate on the "virtual_path" field.
func VirtualPathLT(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLT(FieldVirtualPath, v))
}

// VirtualPathLTE applies the LTE predicate on the "virtual_path" field.
func VirtualPathLTE(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLTE(FieldVirtualPath, v))
}

// VirtualPathContains applies the Contains predicate on the "virtual_path" field.
func VirtualPathContains(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldContains(FieldVirtualPath, v))
}

// VirtualPathHasPrefix applies the HasPrefix predicate on the "virtual_path" field.
func VirtualPathHasPrefix(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldHasPrefix(FieldVirtualPath, v))
}

// VirtualPathHasSuffix applies the HasSuffix predicate on the "virtual_path" field.
func VirtualPathHasSuffix(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldHasSuffix(FieldVirtualPath, v))
}

// VirtualPathEqualFold applies the EqualFold predicate on the "virtual_path" field.
func VirtualPathEqualFold(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEqualFold(FieldVirtualPath, v))
}

// VirtualPathContainsFold applies the ContainsFold predicate on the "virtual_path" field.
func VirtualPathContainsFold(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldContainsFold(FieldVirtualPath, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLTE(FieldSizeBytes, v))
}

// MtimeEQ applies the EQ predicate on the "mtime" field.
func MtimeEQ(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldMtime, v))
}

// MtimeNEQ applies the NEQ predicate on the "mtime" field.
func MtimeNEQ(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNEQ(FieldMtime, v))
}

// MtimeIn applies the In predicate on the "mtime" field.
func MtimeIn(vs ...time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldIn(FieldMtime, vs...))
}

// MtimeNotIn applies the NotIn predicate on the "mtime" field.
func MtimeNotIn(vs ...time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNotIn(FieldMtime, vs...))
}

// MtimeGT applies the GT predicate on the "mtime" field.
func MtimeGT(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGT(FieldMtime, v))
}

// MtimeGTE applies the GTE predicate on the "mtime" field.
func MtimeGTE(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGTE(FieldMtime, v))
}

// MtimeLT applies the LT predicate on the "mtime" field.
func MtimeLT(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLT(FieldMtime, v))
}

// MtimeLTE applies the LTE predicate on the "mtime" field.
func MtimeLTE(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLTE(FieldMtime, v))
}

// Blake3EQ applies the EQ predicate on the "blake3" field.
func Blake3EQ(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldBlake3, v))
}

// Blake3NEQ applies the NEQ predicate on the "blake3" field.
func Blake3NEQ(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNEQ(FieldBlake3, v))
}

// Blake3In applies the In predicate on the "blake3" field.
func Blake3In(vs ...string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldIn(FieldBlake3, vs...))
}

// Blake3NotIn applies the NotIn predicate on the "blake3" field.
func Blake3NotIn(vs ...string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNotIn(FieldBlake3, vs...))
}

// Blake3GT applies the GT predicate on the "blake3" field.
func Blake3GT(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGT(FieldBlake3, v))
}

// Blake3GTE applies the GTE predicate on the "blake3" field.
func Blake3GTE(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGTE(FieldBlake3, v))
}

// Blake3LT applies the LT predicate on the "blake3" field.
func Blake3LT(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLT(FieldBlake3, v))
}

// Blake3LTE applies the LTE predicate on the "blake3" field.
func Blake3LTE(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLTE(FieldBlake3, v))
}

// Blake3Contains applies the Contains predicate on the "blake3" field.
func Blake3Contains(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldContains(FieldBlake3, v))
}

// Blake3HasPrefix applies the HasPrefix predicate on the "blake3" field.
func Blake3HasPrefix(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldHasPrefix(FieldBlake3, v))
}

// Blake3HasSuffix applies the HasSuffix predicate on the "blake3" field.
func Blake3HasSuffix(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldHasSuffix(FieldBlake3, v))
}

// Blake3EqualFold applies the EqualFold predicate on the "blake3" field.
func Blake3EqualFold(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEqualFold(FieldBlake3, v))
}

// Blake3ContainsFold applies the ContainsFold predicate on the "blake3" field.
func Blake3ContainsFold(v string) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldContainsFold(FieldBlake3, v))
}

// BlockSizeEQ applies the EQ predicate on the "block_size" field.
func BlockSizeEQ(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldBlockSize, v))
}

// BlockSizeNEQ applies the NEQ predicate on the "block_size" field.
func BlockSizeNEQ(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNEQ(FieldBlockSize, v))
}

// BlockSizeIn applies the In predicate on the "block_size" field.
func BlockSizeIn(vs ...int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldIn(FieldBlockSize, vs...))
}

// BlockSizeNotIn applies the NotIn predicate on the "block_size" field.
func BlockSizeNotIn(vs ...int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNotIn(FieldBlockSize, vs...))
}

// BlockSizeGT applies the GT predicate on the "block_size" field.
func BlockSizeGT(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGT(FieldBlockSize, v))
}

// BlockSizeGTE applies the GTE predicate on the "block_size" field.
func BlockSizeGTE(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGTE(FieldBlockSize, v))
}

// BlockSizeLT applies the LT predicate on the "block_size" field.
func BlockSizeLT(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLT(FieldBlockSize, v))
}

// BlockSizeLTE applies the LTE predicate on the "block_size" field.
func BlockSizeLTE(v int64) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLTE(FieldBlockSize, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ShareFile {
	return predicate.ShareFile(sql.FieldLTE(FieldCreatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.ShareFile {
	return predicate.ShareFile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.ShareFile {
	return predicate.ShareFile(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasShare applies the HasEdge predicate on the "share" edge.
func HasShare() predicate.ShareFile {
	return predicate.ShareFile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ShareTable, ShareColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShareWith applies the HasEdge predicate on the "share" edge with a given conditions (other predicates).
func HasShareWith(preds ...predicate.TransferShare) predicate.ShareFile {
	return predicate.ShareFile(func(s *sql.Selector) {
		step := newShareStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ShareFile) predicate.ShareFile {
	return predicate.ShareFile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ShareFile) predicate.ShareFile {
	return predicate.ShareFile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ShareFile) predicate.ShareFile {
	return predicate.ShareFile(sql.NotPredicates(p))
}
