// Code generated by ent, DO NOT EDIT.

package transferjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ca-x/tailcat-webui/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldUserID, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldClientID, v))
}

// RemoteShareID applies equality check predicate on the "remote_share_id" field. It's identical to RemoteShareIDEQ.
func RemoteShareID(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldRemoteShareID, v))
}

// RemoteCapabilityCipher applies equality check predicate on the "remote_capability_cipher" field. It's identical to RemoteCapabilityCipherEQ.
func RemoteCapabilityCipher(v []byte) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldRemoteCapabilityCipher, v))
}

// Attempt applies equality check predicate on the "attempt" field. It's identical to AttemptEQ.
func Attempt(v int) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldAttempt, v))
}

// TotalBytes applies equality check predicate on the "total_bytes" field. It's identical to TotalBytesEQ.
func TotalBytes(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldTotalBytes, v))
}

// ReceivedBytes applies equality check predicate on the "received_bytes" field. It's identical to ReceivedBytesEQ.
func ReceivedBytes(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldReceivedBytes, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldFinishedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldContainsFold(FieldUserID, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldContainsFold(FieldClientID, v))
}

// RemoteShareIDEQ applies the EQ predicate on the "remote_share_id" field.
func RemoteShareIDEQ(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldRemoteShareID, v))
}

// RemoteShareIDNEQ applies the NEQ predicate on the "remote_share_id" field.
func RemoteShareIDNEQ(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldRemoteShareID, v))
}

// RemoteShareIDIn applies the In predicate on the "remote_share_id" field.
func RemoteShareIDIn(vs ...string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldRemoteShareID, vs...))
}

// RemoteShareIDNotIn applies the NotIn predicate on the "remote_share_id" field.
func RemoteShareIDNotIn(vs ...string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldRemoteShareID, vs...))
}

// RemoteShareIDGT applies the GT predicate on the "remote_share_id" field.
func RemoteShareIDGT(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGT(FieldRemoteShareID, v))
}

// RemoteShareIDGTE applies the GTE predicate on the "remote_share_id" field.
func RemoteShareIDGTE(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGTE(FieldRemoteShareID, v))
}

// RemoteShareIDLT applies the LT predicate on the "remote_share_id" field.
func RemoteShareIDLT(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLT(FieldRemoteShareID, v))
}

// RemoteShareIDLTE applies the LTE predicate on the "remote_share_id" field.
func RemoteShareIDLTE(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLTE(FieldRemoteShareID, v))
}

// RemoteShareIDContains applies the Contains predicate on the "remote_share_id" field.
func RemoteShareIDContains(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldContains(FieldRemoteShareID, v))
}

// RemoteShareIDHasPrefix applies the HasPrefix predicate on the "remote_share_id" field.
func RemoteShareIDHasPrefix(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldHasPrefix(FieldRemoteShareID, v))
}

// RemoteShareIDHasSuffix applies the HasSuffix predicate on the "remote_share_id" field.
func RemoteShareIDHasSuffix(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldHasSuffix(FieldRemoteShareID, v))
}

// RemoteShareIDEqualFold applies the EqualFold predicate on the "remote_share_id" field.
func RemoteShareIDEqualFold(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEqualFold(FieldRemoteShareID, v))
}

// RemoteShareIDContainsFold applies the ContainsFold predicate on the "remote_share_id" field.
func RemoteShareIDContainsFold(v string) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldContainsFold(FieldRemoteShareID, v))
}

// RemoteCapabilityCipherEQ applies the EQ predicate on the "remote_capability_cipher" field.
func RemoteCapabilityCipherEQ(v []byte) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldRemoteCapabilityCipher, v))
}

// RemoteCapabilityCipherNEQ applies the NEQ predicate on the "remote_capability_cipher" field.
func RemoteCapabilityCipherNEQ(v []byte) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldRemoteCapabilityCipher, v))
}

// RemoteCapabilityCipherIn applies the In predicate on the "remote_capability_cipher" field.
func RemoteCapabilityCipherIn(vs ...[]byte) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldRemoteCapabilityCipher, vs...))
}

// RemoteCapabilityCipherNotIn applies the NotIn predicate on the "remote_capability_cipher" field.
func RemoteCapabilityCipherNotIn(vs ...[]byte) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldRemoteCapabilityCipher, vs...))
}

// RemoteCapabilityCipherGT applies the GT predicate on the "remote_capability_cipher" field.
func RemoteCapabilityCipherGT(v []byte) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGT(FieldRemoteCapabilityCipher, v))
}

// RemoteCapabilityCipherGTE applies the GTE predicate on the "remote_capability_cipher" field.
func RemoteCapabilityCipherGTE(v []byte) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGTE(FieldRemoteCapabilityCipher, v))
}

// RemoteCapabilityCipherLT applies the LT predicate on the "remote_capability_cipher" field.
func RemoteCapabilityCipherLT(v []byte) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLT(FieldRemoteCapabilityCipher, v))
}

// RemoteCapabilityCipherLTE applies the LTE predicate on the "remote_capability_cipher" field.
func RemoteCapabilityCipherLTE(v []byte) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLTE(FieldRemoteCapabilityCipher, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldStatus, vs...))
}

// AttemptEQ applies the EQ predicate on the "attempt" field.
func AttemptEQ(v int) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldAttempt, v))
}

// AttemptNEQ applies the NEQ predicate on the "attempt" field.
func AttemptNEQ(v int) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldAttempt, v))
}

// AttemptIn applies the In predicate on the "attempt" field.
func AttemptIn(vs ...int) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldAttempt, vs...))
}

// AttemptNotIn applies the NotIn predicate on the "attempt" field.
func AttemptNotIn(vs ...int) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldAttempt, vs...))
}

// AttemptGT applies the GT predicate on the "attempt" field.
func AttemptGT(v int) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGT(FieldAttempt, v))
}

// AttemptGTE applies the GTE predicate on the "attempt" field.
func AttemptGTE(v int) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGTE(FieldAttempt, v))
}

// AttemptLT applies the LT predicate on the "attempt" field.
func AttemptLT(v int) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLT(FieldAttempt, v))
}

// AttemptLTE applies the LTE predicate on the "attempt" field.
func AttemptLTE(v int) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLTE(FieldAttempt, v))
}

// AttemptKindEQ applies the EQ predicate on the "attempt_kind" field.
func AttemptKindEQ(v AttemptKind) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldAttemptKind, v))
}

// AttemptKindNEQ applies the NEQ predicate on the "attempt_kind" field.
func AttemptKindNEQ(v AttemptKind) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldAttemptKind, v))
}

// AttemptKindIn applies the In predicate on the "attempt_kind" field.
func AttemptKindIn(vs ...AttemptKind) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldAttemptKind, vs...))
}

// AttemptKindNotIn applies the NotIn predicate on the "attempt_kind" field.
func AttemptKindNotIn(vs ...AttemptKind) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldAttemptKind, vs...))
}

// AttemptKindIsNil applies the IsNil predicate on the "attempt_kind" field.
func AttemptKindIsNil() predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIsNull(FieldAttemptKind))
}

// AttemptKindNotNil applies the NotNil predicate on the "attempt_kind" field.
func AttemptKindNotNil() predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotNull(FieldAttemptKind))
}

// TotalBytesEQ applies the EQ predicate on the "total_bytes" field.
func TotalBytesEQ(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldTotalBytes, v))
}

// TotalBytesNEQ applies the NEQ predicate on the "total_bytes" field.
func TotalBytesNEQ(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldTotalBytes, v))
}

// TotalBytesIn applies the In predicate on the "total_bytes" field.
func TotalBytesIn(vs ...int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldTotalBytes, vs...))
}

// TotalBytesNotIn applies the NotIn predicate on the "total_bytes" field.
func TotalBytesNotIn(vs ...int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldTotalBytes, vs...))
}

// TotalBytesGT applies the GT predicate on the "total_bytes" field.
func TotalBytesGT(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGT(FieldTotalBytes, v))
}

// TotalBytesGTE applies the GTE predicate on the "total_bytes" field.
func TotalBytesGTE(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGTE(FieldTotalBytes, v))
}

// TotalBytesLT applies the LT predicate on the "total_bytes" field.
func TotalBytesLT(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLT(FieldTotalBytes, v))
}

// TotalBytesLTE applies the LTE predicate on the "total_bytes" field.
func TotalBytesLTE(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLTE(FieldTotalBytes, v))
}

// ReceivedBytesEQ applies the EQ predicate on the "received_bytes" field.
func ReceivedBytesEQ(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldReceivedBytes, v))
}

// ReceivedBytesNEQ applies the NEQ predicate on the "received_bytes" field.
func ReceivedBytesNEQ(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldReceivedBytes, v))
}

// ReceivedBytesIn applies the In predicate on the "received_bytes" field.
func ReceivedBytesIn(vs ...int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldReceivedBytes, vs...))
}

// ReceivedBytesNotIn applies the NotIn predicate on the "received_bytes" field.
func ReceivedBytesNotIn(vs ...int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldReceivedBytes, vs...))
}

// ReceivedBytesGT applies the GT predicate on the "received_bytes" field.
func ReceivedBytesGT(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGT(FieldReceivedBytes, v))
}

// ReceivedBytesGTE applies the GTE predicate on the "received_bytes" field.
func ReceivedBytesGTE(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGTE(FieldReceivedBytes, v))
}

// ReceivedBytesLT applies the LT predicate on the "received_bytes" field.
func ReceivedBytesLT(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLT(FieldReceivedBytes, v))
}

// ReceivedBytesLTE applies the LTE predicate on the "received_bytes" field.
func ReceivedBytesLTE(v int64) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLTE(FieldReceivedBytes, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotNull(FieldFinishedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLTE(FieldExpiresAt, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v ErrorCode) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v ErrorCode) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...ErrorCode) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...ErrorCode) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotNull(FieldErrorCode))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TransferJob {
	return predicate.TransferJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.TransferJob {
	return predicate.TransferJob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.TransferJob {
	return predicate.TransferJob(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClient applies the HasEdge predicate on the "client" edge.
func HasClient() predicate.TransferJob {
	return predicate.TransferJob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClientTable, ClientColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClientWith applies the HasEdge predicate on the "client" edge with a given conditions (other predicates).
func HasClientWith(preds ...predicate.TailClient) predicate.TransferJob {
	return predicate.TransferJob(func(s *sql.Selector) {
		step := newClientStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.TransferJob {
	return predicate.TransferJob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.TransferItem) predicate.TransferJob {
	return predicate.TransferJob(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TransferJob) predicate.TransferJob {
	return predicate.TransferJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TransferJob) predicate.TransferJob {
	return predicate.TransferJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TransferJob) predicate.TransferJob {
	return predicate.TransferJob(sql.NotPredicates(p))
}
