// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AllowedClientsColumns holds the columns for the "allowed_clients" table.
	AllowedClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "public_key", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "server_id", Type: field.TypeString},
	}
	// AllowedClientsTable holds the schema information for the "allowed_clients" table.
	AllowedClientsTable = &schema.Table{
		Name:       "allowed_clients",
		Columns:    AllowedClientsColumns,
		PrimaryKey: []*schema.Column{AllowedClientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "allowed_clients_tail_servers_allowed_clients",
				Columns:    []*schema.Column{AllowedClientsColumns[5]},
				RefColumns: []*schema.Column{TailServersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "allowedclient_server_id_public_key",
				Unique:  true,
				Columns: []*schema.Column{AllowedClientsColumns[5], AllowedClientsColumns[3]},
			},
			{
				Name:    "allowedclient_user_id",
				Unique:  false,
				Columns: []*schema.Column{AllowedClientsColumns[1]},
			},
		},
	}
	// AuditEventsColumns holds the columns for the "audit_events" table.
	AuditEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "resource_kind", Type: field.TypeString, Nullable: true},
		{Name: "resource_id", Type: field.TypeString, Nullable: true},
		{Name: "outcome", Type: field.TypeEnum, Enums: []string{"success", "failure"}, Default: "success"},
		{Name: "request_id", Type: field.TypeString, Nullable: true},
		{Name: "detail", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString, Nullable: true},
	}
	// AuditEventsTable holds the schema information for the "audit_events" table.
	AuditEventsTable = &schema.Table{
		Name:       "audit_events",
		Columns:    AuditEventsColumns,
		PrimaryKey: []*schema.Column{AuditEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "audit_events_users_audit_events",
				Columns:    []*schema.Column{AuditEventsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "auditevent_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditEventsColumns[8], AuditEventsColumns[7]},
			},
			{
				Name:    "auditevent_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditEventsColumns[7]},
			},
			{
				Name:    "auditevent_resource_kind_resource_id",
				Unique:  false,
				Columns: []*schema.Column{AuditEventsColumns[2], AuditEventsColumns[3]},
			},
		},
	}
	// DiagnosticRunsColumns holds the columns for the "diagnostic_runs" table.
	DiagnosticRunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"ping", "throughput"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"running", "succeeded", "failed", "canceled", "interrupted"}, Default: "running"},
		{Name: "path", Type: field.TypeEnum, Nullable: true, Enums: []string{"direct", "derp", "peer_relay"}},
		{Name: "latency_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "upload_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "download_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "upload_bps", Type: field.TypeInt64, Default: 0},
		{Name: "download_bps", Type: field.TypeInt64, Default: 0},
		{Name: "error_code", Type: field.TypeEnum, Nullable: true, Enums: []string{"diagnostic_canceled", "diagnostic_timeout", "diagnostic_invalid_magic", "diagnostic_header_too_large", "diagnostic_malformed_header", "diagnostic_invalid_request", "diagnostic_limit_exceeded", "diagnostic_io", "diagnostic_invalid_runner"}},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "client_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// DiagnosticRunsTable holds the schema information for the "diagnostic_runs" table.
	DiagnosticRunsTable = &schema.Table{
		Name:       "diagnostic_runs",
		Columns:    DiagnosticRunsColumns,
		PrimaryKey: []*schema.Column{DiagnosticRunsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "diagnostic_runs_tail_clients_diagnostic_runs",
				Columns:    []*schema.Column{DiagnosticRunsColumns[12]},
				RefColumns: []*schema.Column{TailClientsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "diagnostic_runs_users_diagnostic_runs",
				Columns:    []*schema.Column{DiagnosticRunsColumns[13]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "diagnosticrun_user_id_started_at",
				Unique:  false,
				Columns: []*schema.Column{DiagnosticRunsColumns[13], DiagnosticRunsColumns[10]},
			},
			{
				Name:    "diagnosticrun_client_id_started_at",
				Unique:  false,
				Columns: []*schema.Column{DiagnosticRunsColumns[12], DiagnosticRunsColumns[10]},
			},
		},
	}
	// ExitRulesColumns holds the columns for the "exit_rules" table.
	ExitRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "prefix", Type: field.TypeString},
		{Name: "start_port", Type: field.TypeUint16},
		{Name: "end_port", Type: field.TypeUint16},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "server_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// ExitRulesTable holds the schema information for the "exit_rules" table.
	ExitRulesTable = &schema.Table{
		Name:       "exit_rules",
		Columns:    ExitRulesColumns,
		PrimaryKey: []*schema.Column{ExitRulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "exit_rules_tail_servers_exit_rules",
				Columns:    []*schema.Column{ExitRulesColumns[7]},
				RefColumns: []*schema.Column{TailServersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "exit_rules_users_exit_rules",
				Columns:    []*schema.Column{ExitRulesColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "exitrule_server_id_prefix_start_port_end_port",
				Unique:  true,
				Columns: []*schema.Column{ExitRulesColumns[7], ExitRulesColumns[1], ExitRulesColumns[2], ExitRulesColumns[3]},
			},
			{
				Name:    "exitrule_user_id",
				Unique:  false,
				Columns: []*schema.Column{ExitRulesColumns[8]},
			},
		},
	}
	// LoginFlowsColumns holds the columns for the "login_flows" table.
	LoginFlowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "state_hash", Type: field.TypeString, Unique: true},
		{Name: "nonce", Type: field.TypeString},
		{Name: "code_verifier", Type: field.TypeString},
		{Name: "return_to", Type: field.TypeString, Default: "/"},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// LoginFlowsTable holds the schema information for the "login_flows" table.
	LoginFlowsTable = &schema.Table{
		Name:       "login_flows",
		Columns:    LoginFlowsColumns,
		PrimaryKey: []*schema.Column{LoginFlowsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "loginflow_expires_at",
				Unique:  false,
				Columns: []*schema.Column{LoginFlowsColumns[5]},
			},
		},
	}
	// PortMappingsColumns holds the columns for the "port_mappings" table.
	PortMappingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"tcp", "no_auth_ssh"}, Default: "tcp"},
		{Name: "listen_port", Type: field.TypeUint16},
		{Name: "target_host", Type: field.TypeString, Default: "127.0.0.1"},
		{Name: "target_port", Type: field.TypeUint16},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "server_id", Type: field.TypeString},
	}
	// PortMappingsTable holds the schema information for the "port_mappings" table.
	PortMappingsTable = &schema.Table{
		Name:       "port_mappings",
		Columns:    PortMappingsColumns,
		PrimaryKey: []*schema.Column{PortMappingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "port_mappings_tail_servers_mappings",
				Columns:    []*schema.Column{PortMappingsColumns[10]},
				RefColumns: []*schema.Column{TailServersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "portmapping_server_id_listen_port",
				Unique:  true,
				Columns: []*schema.Column{PortMappingsColumns[10], PortMappingsColumns[4]},
			},
			{
				Name:    "portmapping_user_id",
				Unique:  false,
				Columns: []*schema.Column{PortMappingsColumns[1]},
			},
		},
	}
	// PublishedRoutesColumns holds the columns for the "published_routes" table.
	PublishedRoutesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "remote_port", Type: field.TypeUint16},
		{Name: "base_path", Type: field.TypeString, Default: "/"},
		{Name: "access", Type: field.TypeEnum, Enums: []string{"private", "public"}, Default: "private"},
		{Name: "allowed_methods", Type: field.TypeJSON},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "client_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// PublishedRoutesTable holds the schema information for the "published_routes" table.
	PublishedRoutesTable = &schema.Table{
		Name:       "published_routes",
		Columns:    PublishedRoutesColumns,
		PrimaryKey: []*schema.Column{PublishedRoutesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "published_routes_tail_clients_routes",
				Columns:    []*schema.Column{PublishedRoutesColumns[10]},
				RefColumns: []*schema.Column{TailClientsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "published_routes_users_routes",
				Columns:    []*schema.Column{PublishedRoutesColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "publishedroute_user_id",
				Unique:  false,
				Columns: []*schema.Column{PublishedRoutesColumns[11]},
			},
			{
				Name:    "publishedroute_client_id",
				Unique:  false,
				Columns: []*schema.Column{PublishedRoutesColumns[10]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "session_user_id_expires_at",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[5], SessionsColumns[2]},
			},
			{
				Name:    "session_expires_at",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[2]},
			},
		},
	}
	// ShareFilesColumns holds the columns for the "share_files" table.
	ShareFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "storage_name", Type: field.TypeString},
		{Name: "virtual_path", Type: field.TypeString},
		{Name: "size_bytes", Type: field.TypeInt64},
		{Name: "mtime", Type: field.TypeTime},
		{Name: "blake3", Type: field.TypeString},
		{Name: "block_size", Type: field.TypeInt64, Default: 8388608},
		{Name: "block_hashes", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "share_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// ShareFilesTable holds the schema information for the "share_files" table.
	ShareFilesTable = &schema.Table{
		Name:       "share_files",
		Columns:    ShareFilesColumns,
		PrimaryKey: []*schema.Column{ShareFilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "share_files_transfer_shares_files",
				Columns:    []*schema.Column{ShareFilesColumns[9]},
				RefColumns: []*schema.Column{TransferSharesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "share_files_users_share_files",
				Columns:    []*schema.Column{ShareFilesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "sharefile_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{ShareFilesColumns[10], ShareFilesColumns[8]},
			},
			{
				Name:    "sharefile_share_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{ShareFilesColumns[9], ShareFilesColumns[8]},
			},
			{
				Name:    "sharefile_share_id_virtual_path",
				Unique:  true,
				Columns: []*schema.Column{ShareFilesColumns[9], ShareFilesColumns[2]},
			},
		},
	}
	// TailClientsColumns holds the columns for the "tail_clients" table.
	TailClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "server_token_cipher", Type: field.TypeBytes},
		{Name: "token_hint", Type: field.TypeString},
		{Name: "key_cipher", Type: field.TypeBytes, Nullable: true},
		{Name: "derp_map_url", Type: field.TypeString, Nullable: true},
		{Name: "last_ping_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "last_path", Type: field.TypeString, Nullable: true},
		{Name: "last_ping_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString},
	}
	// TailClientsTable holds the schema information for the "tail_clients" table.
	TailClientsTable = &schema.Table{
		Name:       "tail_clients",
		Columns:    TailClientsColumns,
		PrimaryKey: []*schema.Column{TailClientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tail_clients_users_clients",
				Columns:    []*schema.Column{TailClientsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tailclient_user_id_name",
				Unique:  true,
				Columns: []*schema.Column{TailClientsColumns[11], TailClientsColumns[1]},
			},
		},
	}
	// TailServersColumns holds the columns for the "tail_servers" table.
	TailServersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "key_mode", Type: field.TypeEnum, Enums: []string{"ephemeral", "saved"}, Default: "ephemeral"},
		{Name: "key_cipher", Type: field.TypeBytes, Nullable: true},
		{Name: "region", Type: field.TypeString, Default: "auto"},
		{Name: "derp_map_url", Type: field.TypeString, Nullable: true},
		{Name: "allowlist_enabled", Type: field.TypeBool, Default: false},
		{Name: "exit_node_enabled", Type: field.TypeBool, Default: false},
		{Name: "desired_running", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString},
	}
	// TailServersTable holds the schema information for the "tail_servers" table.
	TailServersTable = &schema.Table{
		Name:       "tail_servers",
		Columns:    TailServersColumns,
		PrimaryKey: []*schema.Column{TailServersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tail_servers_users_servers",
				Columns:    []*schema.Column{TailServersColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tailserver_user_id_name",
				Unique:  true,
				Columns: []*schema.Column{TailServersColumns[11], TailServersColumns[1]},
			},
		},
	}
	// TransferItemsColumns holds the columns for the "transfer_items" table.
	TransferItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "remote_file_id", Type: field.TypeString},
		{Name: "storage_name", Type: field.TypeString},
		{Name: "virtual_path", Type: field.TypeString},
		{Name: "size_bytes", Type: field.TypeInt64},
		{Name: "mtime", Type: field.TypeTime},
		{Name: "blake3", Type: field.TypeString},
		{Name: "block_size", Type: field.TypeInt64, Default: 8388608},
		{Name: "block_hashes", Type: field.TypeJSON},
		{Name: "completed_blocks", Type: field.TypeJSON},
		{Name: "received_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"staging", "ready", "running", "completed", "failed", "canceled", "interrupted", "expired", "deleting"}, Default: "staging"},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "error_code", Type: field.TypeEnum, Nullable: true, Enums: []string{"transfer_canceled", "transfer_expired", "transfer_remote_unavailable", "transfer_invalid_capability", "transfer_share_not_found", "transfer_protocol_invalid", "transfer_integrity_mismatch", "transfer_storage_failed", "transfer_limit_exceeded"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "job_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// TransferItemsTable holds the schema information for the "transfer_items" table.
	TransferItemsTable = &schema.Table{
		Name:       "transfer_items",
		Columns:    TransferItemsColumns,
		PrimaryKey: []*schema.Column{TransferItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transfer_items_transfer_jobs_items",
				Columns:    []*schema.Column{TransferItemsColumns[17]},
				RefColumns: []*schema.Column{TransferJobsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "transfer_items_users_transfer_items",
				Columns:    []*schema.Column{TransferItemsColumns[18]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "transferitem_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{TransferItemsColumns[18], TransferItemsColumns[15]},
			},
			{
				Name:    "transferitem_job_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{TransferItemsColumns[17], TransferItemsColumns[15]},
			},
			{
				Name:    "transferitem_job_id_remote_file_id",
				Unique:  true,
				Columns: []*schema.Column{TransferItemsColumns[17], TransferItemsColumns[1]},
			},
		},
	}
	// TransferJobsColumns holds the columns for the "transfer_jobs" table.
	TransferJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "remote_share_id", Type: field.TypeString},
		{Name: "remote_capability_cipher", Type: field.TypeBytes},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"staging", "ready", "running", "completed", "failed", "canceled", "interrupted", "expired", "deleting"}, Default: "staging"},
		{Name: "total_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "received_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "error_code", Type: field.TypeEnum, Nullable: true, Enums: []string{"transfer_canceled", "transfer_expired", "transfer_remote_unavailable", "transfer_invalid_capability", "transfer_share_not_found", "transfer_protocol_invalid", "transfer_integrity_mismatch", "transfer_storage_failed", "transfer_limit_exceeded"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "client_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// TransferJobsTable holds the schema information for the "transfer_jobs" table.
	TransferJobsTable = &schema.Table{
		Name:       "transfer_jobs",
		Columns:    TransferJobsColumns,
		PrimaryKey: []*schema.Column{TransferJobsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transfer_jobs_tail_clients_transfer_jobs",
				Columns:    []*schema.Column{TransferJobsColumns[12]},
				RefColumns: []*schema.Column{TailClientsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "transfer_jobs_users_transfer_jobs",
				Columns:    []*schema.Column{TransferJobsColumns[13]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "transferjob_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{TransferJobsColumns[13], TransferJobsColumns[10]},
			},
			{
				Name:    "transferjob_user_id_status_expires_at",
				Unique:  false,
				Columns: []*schema.Column{TransferJobsColumns[13], TransferJobsColumns[3], TransferJobsColumns[8]},
			},
			{
				Name:    "transferjob_status_expires_at",
				Unique:  false,
				Columns: []*schema.Column{TransferJobsColumns[3], TransferJobsColumns[8]},
			},
			{
				Name:    "transferjob_client_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{TransferJobsColumns[12], TransferJobsColumns[10]},
			},
		},
	}
	// TransferSharesColumns holds the columns for the "transfer_shares" table.
	TransferSharesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"staging", "ready", "running", "completed", "failed", "canceled", "interrupted", "expired", "deleting"}, Default: "staging"},
		{Name: "capability_hash", Type: field.TypeBytes},
		{Name: "total_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "file_count", Type: field.TypeInt, Default: 0},
		{Name: "ready_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "error_code", Type: field.TypeEnum, Nullable: true, Enums: []string{"transfer_canceled", "transfer_expired", "transfer_remote_unavailable", "transfer_invalid_capability", "transfer_share_not_found", "transfer_protocol_invalid", "transfer_integrity_mismatch", "transfer_storage_failed", "transfer_limit_exceeded"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "server_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// TransferSharesTable holds the schema information for the "transfer_shares" table.
	TransferSharesTable = &schema.Table{
		Name:       "transfer_shares",
		Columns:    TransferSharesColumns,
		PrimaryKey: []*schema.Column{TransferSharesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transfer_shares_tail_servers_transfer_shares",
				Columns:    []*schema.Column{TransferSharesColumns[11]},
				RefColumns: []*schema.Column{TailServersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "transfer_shares_users_transfer_shares",
				Columns:    []*schema.Column{TransferSharesColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "transfershare_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{TransferSharesColumns[12], TransferSharesColumns[9]},
			},
			{
				Name:    "transfershare_user_id_status_expires_at",
				Unique:  false,
				Columns: []*schema.Column{TransferSharesColumns[12], TransferSharesColumns[1], TransferSharesColumns[7]},
			},
			{
				Name:    "transfershare_status_expires_at",
				Unique:  false,
				Columns: []*schema.Column{TransferSharesColumns[1], TransferSharesColumns[7]},
			},
			{
				Name:    "transfershare_server_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{TransferSharesColumns[11], TransferSharesColumns[9]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "issuer", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_issuer_subject",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1], UsersColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AllowedClientsTable,
		AuditEventsTable,
		DiagnosticRunsTable,
		ExitRulesTable,
		LoginFlowsTable,
		PortMappingsTable,
		PublishedRoutesTable,
		SessionsTable,
		ShareFilesTable,
		TailClientsTable,
		TailServersTable,
		TransferItemsTable,
		TransferJobsTable,
		TransferSharesTable,
		UsersTable,
	}
)

func init() {
	AllowedClientsTable.ForeignKeys[0].RefTable = TailServersTable
	AuditEventsTable.ForeignKeys[0].RefTable = UsersTable
	DiagnosticRunsTable.ForeignKeys[0].RefTable = TailClientsTable
	DiagnosticRunsTable.ForeignKeys[1].RefTable = UsersTable
	ExitRulesTable.ForeignKeys[0].RefTable = TailServersTable
	ExitRulesTable.ForeignKeys[1].RefTable = UsersTable
	PortMappingsTable.ForeignKeys[0].RefTable = TailServersTable
	PublishedRoutesTable.ForeignKeys[0].RefTable = TailClientsTable
	PublishedRoutesTable.ForeignKeys[1].RefTable = UsersTable
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
	ShareFilesTable.ForeignKeys[0].RefTable = TransferSharesTable
	ShareFilesTable.ForeignKeys[1].RefTable = UsersTable
	TailClientsTable.ForeignKeys[0].RefTable = UsersTable
	TailServersTable.ForeignKeys[0].RefTable = UsersTable
	TransferItemsTable.ForeignKeys[0].RefTable = TransferJobsTable
	TransferItemsTable.ForeignKeys[1].RefTable = UsersTable
	TransferJobsTable.ForeignKeys[0].RefTable = TailClientsTable
	TransferJobsTable.ForeignKeys[1].RefTable = UsersTable
	TransferSharesTable.ForeignKeys[0].RefTable = TailServersTable
	TransferSharesTable.ForeignKeys[1].RefTable = UsersTable
}
