// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/tailcat-webui/ent/loginflow"
)

// LoginFlowCreate is the builder for creating a LoginFlow entity.
type LoginFlowCreate struct {
	config
	mutation *LoginFlowMutation
	hooks    []Hook
}

// SetStateHash sets the "state_hash" field.
func (_c *LoginFlowCreate) SetStateHash(v string) *LoginFlowCreate {
	_c.mutation.SetStateHash(v)
	return _c
}

// SetNonce sets the "nonce" field.
func (_c *LoginFlowCreate) SetNonce(v string) *LoginFlowCreate {
	_c.mutation.SetNonce(v)
	return _c
}

// SetCodeVerifier sets the "code_verifier" field.
func (_c *LoginFlowCreate) SetCodeVerifier(v string) *LoginFlowCreate {
	_c.mutation.SetCodeVerifier(v)
	return _c
}

// SetReturnTo sets the "return_to" field.
func (_c *LoginFlowCreate) SetReturnTo(v string) *LoginFlowCreate {
	_c.mutation.SetReturnTo(v)
	return _c
}

// SetNillableReturnTo sets the "return_to" field if the given value is not nil.
func (_c *LoginFlowCreate) SetNillableReturnTo(v *string) *LoginFlowCreate {
	if v != nil {
		_c.SetReturnTo(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *LoginFlowCreate) SetExpiresAt(v time.Time) *LoginFlowCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LoginFlowCreate) SetCreatedAt(v time.Time) *LoginFlowCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LoginFlowCreate) SetNillableCreatedAt(v *time.Time) *LoginFlowCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LoginFlowCreate) SetID(v string) *LoginFlowCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LoginFlowCreate) SetNillableID(v *string) *LoginFlowCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the LoginFlowMutation object of the builder.
func (_c *LoginFlowCreate) Mutation() *LoginFlowMutation {
	return _c.mutation
}

// Save creates the LoginFlow in the database.
func (_c *LoginFlowCreate) Save(ctx context.Context) (*LoginFlow, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LoginFlowCreate) SaveX(ctx context.Context) *LoginFlow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoginFlowCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoginFlowCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LoginFlowCreate) defaults() {
	if _, ok := _c.mutation.ReturnTo(); !ok {
		v := loginflow.DefaultReturnTo
		_c.mutation.SetReturnTo(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := loginflow.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := loginflow.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LoginFlowCreate) check() error {
	if _, ok := _c.mutation.StateHash(); !ok {
		return &ValidationError{Name: "state_hash", err: errors.New(`ent: missing required field "LoginFlow.state_hash"`)}
	}
	if _, ok := _c.mutation.Nonce(); !ok {
		return &ValidationError{Name: "nonce", err: errors.New(`ent: missing required field "LoginFlow.nonce"`)}
	}
	if _, ok := _c.mutation.CodeVerifier(); !ok {
		return &ValidationError{Name: "code_verifier", err: errors.New(`ent: missing required field "LoginFlow.code_verifier"`)}
	}
	if _, ok := _c.mutation.ReturnTo(); !ok {
		return &ValidationError{Name: "return_to", err: errors.New(`ent: missing required field "LoginFlow.return_to"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "LoginFlow.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LoginFlow.created_at"`)}
	}
	return nil
}

func (_c *LoginFlowCreate) sqlSave(ctx context.Context) (*LoginFlow, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected LoginFlow.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LoginFlowCreate) createSpec() (*LoginFlow, *sqlgraph.CreateSpec) {
	var (
		_node = &LoginFlow{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(loginflow.Table, sqlgraph.NewFieldSpec(loginflow.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.StateHash(); ok {
		_spec.SetField(loginflow.FieldStateHash, field.TypeString, value)
		_node.StateHash = value
	}
	if value, ok := _c.mutation.Nonce(); ok {
		_spec.SetField(loginflow.FieldNonce, field.TypeString, value)
		_node.Nonce = value
	}
	if value, ok := _c.mutation.CodeVerifier(); ok {
		_spec.SetField(loginflow.FieldCodeVerifier, field.TypeString, value)
		_node.CodeVerifier = value
	}
	if value, ok := _c.mutation.ReturnTo(); ok {
		_spec.SetField(loginflow.FieldReturnTo, field.TypeString, value)
		_node.ReturnTo = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(loginflow.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(loginflow.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// LoginFlowCreateBulk is the builder for creating many LoginFlow entities in bulk.
type LoginFlowCreateBulk struct {
	config
	err      error
	builders []*LoginFlowCreate
}

// Save creates the LoginFlow entities in the database.
func (_c *LoginFlowCreateBulk) Save(ctx context.Context) ([]*LoginFlow, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LoginFlow, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoginFlowMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LoginFlowCreateBulk) SaveX(ctx context.Context) []*LoginFlow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoginFlowCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoginFlowCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
