// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/tailcat-webui/ent/portmapping"
	"github.com/ca-x/tailcat-webui/ent/predicate"
)

// PortMappingUpdate is the builder for updating PortMapping entities.
type PortMappingUpdate struct {
	config
	hooks    []Hook
	mutation *PortMappingMutation
}

// Where appends a list predicates to the PortMappingUpdate builder.
func (_u *PortMappingUpdate) Where(ps ...predicate.PortMapping) *PortMappingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PortMappingUpdate) SetName(v string) *PortMappingUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PortMappingUpdate) SetNillableName(v *string) *PortMappingUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *PortMappingUpdate) SetKind(v portmapping.Kind) *PortMappingUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *PortMappingUpdate) SetNillableKind(v *portmapping.Kind) *PortMappingUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetListenPort sets the "listen_port" field.
func (_u *PortMappingUpdate) SetListenPort(v uint16) *PortMappingUpdate {
	_u.mutation.ResetListenPort()
	_u.mutation.SetListenPort(v)
	return _u
}

// SetNillableListenPort sets the "listen_port" field if the given value is not nil.
func (_u *PortMappingUpdate) SetNillableListenPort(v *uint16) *PortMappingUpdate {
	if v != nil {
		_u.SetListenPort(*v)
	}
	return _u
}

// AddListenPort adds value to the "listen_port" field.
func (_u *PortMappingUpdate) AddListenPort(v int16) *PortMappingUpdate {
	_u.mutation.AddListenPort(v)
	return _u
}

// SetTargetHost sets the "target_host" field.
func (_u *PortMappingUpdate) SetTargetHost(v string) *PortMappingUpdate {
	_u.mutation.SetTargetHost(v)
	return _u
}

// SetNillableTargetHost sets the "target_host" field if the given value is not nil.
func (_u *PortMappingUpdate) SetNillableTargetHost(v *string) *PortMappingUpdate {
	if v != nil {
		_u.SetTargetHost(*v)
	}
	return _u
}

// SetTargetPort sets the "target_port" field.
func (_u *PortMappingUpdate) SetTargetPort(v uint16) *PortMappingUpdate {
	_u.mutation.ResetTargetPort()
	_u.mutation.SetTargetPort(v)
	return _u
}

// SetNillableTargetPort sets the "target_port" field if the given value is not nil.
func (_u *PortMappingUpdate) SetNillableTargetPort(v *uint16) *PortMappingUpdate {
	if v != nil {
		_u.SetTargetPort(*v)
	}
	return _u
}

// AddTargetPort adds value to the "target_port" field.
func (_u *PortMappingUpdate) AddTargetPort(v int16) *PortMappingUpdate {
	_u.mutation.AddTargetPort(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PortMappingUpdate) SetEnabled(v bool) *PortMappingUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PortMappingUpdate) SetNillableEnabled(v *bool) *PortMappingUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PortMappingUpdate) SetUpdatedAt(v time.Time) *PortMappingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PortMappingMutation object of the builder.
func (_u *PortMappingUpdate) Mutation() *PortMappingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PortMappingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PortMappingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PortMappingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PortMappingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PortMappingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := portmapping.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PortMappingUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := portmapping.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PortMapping.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := portmapping.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "PortMapping.kind": %w`, err)}
		}
	}
	if _u.mutation.ServerCleared() && len(_u.mutation.ServerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PortMapping.server"`)
	}
	return nil
}

func (_u *PortMappingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(portmapping.Table, portmapping.Columns, sqlgraph.NewFieldSpec(portmapping.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(portmapping.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(portmapping.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ListenPort(); ok {
		_spec.SetField(portmapping.FieldListenPort, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedListenPort(); ok {
		_spec.AddField(portmapping.FieldListenPort, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.TargetHost(); ok {
		_spec.SetField(portmapping.FieldTargetHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetPort(); ok {
		_spec.SetField(portmapping.FieldTargetPort, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedTargetPort(); ok {
		_spec.AddField(portmapping.FieldTargetPort, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(portmapping.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(portmapping.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{portmapping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PortMappingUpdateOne is the builder for updating a single PortMapping entity.
type PortMappingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PortMappingMutation
}

// SetName sets the "name" field.
func (_u *PortMappingUpdateOne) SetName(v string) *PortMappingUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PortMappingUpdateOne) SetNillableName(v *string) *PortMappingUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *PortMappingUpdateOne) SetKind(v portmapping.Kind) *PortMappingUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *PortMappingUpdateOne) SetNillableKind(v *portmapping.Kind) *PortMappingUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetListenPort sets the "listen_port" field.
func (_u *PortMappingUpdateOne) SetListenPort(v uint16) *PortMappingUpdateOne {
	_u.mutation.ResetListenPort()
	_u.mutation.SetListenPort(v)
	return _u
}

// SetNillableListenPort sets the "listen_port" field if the given value is not nil.
func (_u *PortMappingUpdateOne) SetNillableListenPort(v *uint16) *PortMappingUpdateOne {
	if v != nil {
		_u.SetListenPort(*v)
	}
	return _u
}

// AddListenPort adds value to the "listen_port" field.
func (_u *PortMappingUpdateOne) AddListenPort(v int16) *PortMappingUpdateOne {
	_u.mutation.AddListenPort(v)
	return _u
}

// SetTargetHost sets the "target_host" field.
func (_u *PortMappingUpdateOne) SetTargetHost(v string) *PortMappingUpdateOne {
	_u.mutation.SetTargetHost(v)
	return _u
}

// SetNillableTargetHost sets the "target_host" field if the given value is not nil.
func (_u *PortMappingUpdateOne) SetNillableTargetHost(v *string) *PortMappingUpdateOne {
	if v != nil {
		_u.SetTargetHost(*v)
	}
	return _u
}

// SetTargetPort sets the "target_port" field.
func (_u *PortMappingUpdateOne) SetTargetPort(v uint16) *PortMappingUpdateOne {
	_u.mutation.ResetTargetPort()
	_u.mutation.SetTargetPort(v)
	return _u
}

// SetNillableTargetPort sets the "target_port" field if the given value is not nil.
func (_u *PortMappingUpdateOne) SetNillableTargetPort(v *uint16) *PortMappingUpdateOne {
	if v != nil {
		_u.SetTargetPort(*v)
	}
	return _u
}

// AddTargetPort adds value to the "target_port" field.
func (_u *PortMappingUpdateOne) AddTargetPort(v int16) *PortMappingUpdateOne {
	_u.mutation.AddTargetPort(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PortMappingUpdateOne) SetEnabled(v bool) *PortMappingUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PortMappingUpdateOne) SetNillableEnabled(v *bool) *PortMappingUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PortMappingUpdateOne) SetUpdatedAt(v time.Time) *PortMappingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PortMappingMutation object of the builder.
func (_u *PortMappingUpdateOne) Mutation() *PortMappingMutation {
	return _u.mutation
}

// Where appends a list predicates to the PortMappingUpdate builder.
func (_u *PortMappingUpdateOne) Where(ps ...predicate.PortMapping) *PortMappingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PortMappingUpdateOne) Select(field string, fields ...string) *PortMappingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PortMapping entity.
func (_u *PortMappingUpdateOne) Save(ctx context.Context) (*PortMapping, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PortMappingUpdateOne) SaveX(ctx context.Context) *PortMapping {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PortMappingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PortMappingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PortMappingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := portmapping.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PortMappingUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := portmapping.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PortMapping.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := portmapping.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "PortMapping.kind": %w`, err)}
		}
	}
	if _u.mutation.ServerCleared() && len(_u.mutation.ServerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PortMapping.server"`)
	}
	return nil
}

func (_u *PortMappingUpdateOne) sqlSave(ctx context.Context) (_node *PortMapping, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(portmapping.Table, portmapping.Columns, sqlgraph.NewFieldSpec(portmapping.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PortMapping.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, portmapping.FieldID)
		for _, f := range fields {
			if !portmapping.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != portmapping.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(portmapping.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(portmapping.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ListenPort(); ok {
		_spec.SetField(portmapping.FieldListenPort, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedListenPort(); ok {
		_spec.AddField(portmapping.FieldListenPort, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.TargetHost(); ok {
		_spec.SetField(portmapping.FieldTargetHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetPort(); ok {
		_spec.SetField(portmapping.FieldTargetPort, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedTargetPort(); ok {
		_spec.AddField(portmapping.FieldTargetPort, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(portmapping.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(portmapping.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PortMapping{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{portmapping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
