// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/tailcat-webui/ent/predicate"
	"github.com/ca-x/tailcat-webui/ent/publishedroute"
	"github.com/ca-x/tailcat-webui/ent/tailclient"
	"github.com/ca-x/tailcat-webui/ent/user"
)

// PublishedRouteQuery is the builder for querying PublishedRoute entities.
type PublishedRouteQuery struct {
	config
	ctx        *QueryContext
	order      []publishedroute.OrderOption
	inters     []Interceptor
	predicates []predicate.PublishedRoute
	withOwner  *UserQuery
	withClient *TailClientQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PublishedRouteQuery builder.
func (_q *PublishedRouteQuery) Where(ps ...predicate.PublishedRoute) *PublishedRouteQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PublishedRouteQuery) Limit(limit int) *PublishedRouteQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PublishedRouteQuery) Offset(offset int) *PublishedRouteQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PublishedRouteQuery) Unique(unique bool) *PublishedRouteQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PublishedRouteQuery) Order(o ...publishedroute.OrderOption) *PublishedRouteQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOwner chains the current query on the "owner" edge.
func (_q *PublishedRouteQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(publishedroute.Table, publishedroute.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, publishedroute.OwnerTable, publishedroute.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryClient chains the current query on the "client" edge.
func (_q *PublishedRouteQuery) QueryClient() *TailClientQuery {
	query := (&TailClientClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(publishedroute.Table, publishedroute.FieldID, selector),
			sqlgraph.To(tailclient.Table, tailclient.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, publishedroute.ClientTable, publishedroute.ClientColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PublishedRoute entity from the query.
// Returns a *NotFoundError when no PublishedRoute was found.
func (_q *PublishedRouteQuery) First(ctx context.Context) (*PublishedRoute, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{publishedroute.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PublishedRouteQuery) FirstX(ctx context.Context) *PublishedRoute {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PublishedRoute ID from the query.
// Returns a *NotFoundError when no PublishedRoute ID was found.
func (_q *PublishedRouteQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{publishedroute.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PublishedRouteQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PublishedRoute entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PublishedRoute entity is found.
// Returns a *NotFoundError when no PublishedRoute entities are found.
func (_q *PublishedRouteQuery) Only(ctx context.Context) (*PublishedRoute, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{publishedroute.Label}
	default:
		return nil, &NotSingularError{publishedroute.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PublishedRouteQuery) OnlyX(ctx context.Context) *PublishedRoute {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PublishedRoute ID in the query.
// Returns a *NotSingularError when more than one PublishedRoute ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PublishedRouteQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{publishedroute.Label}
	default:
		err = &NotSingularError{publishedroute.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PublishedRouteQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PublishedRoutes.
func (_q *PublishedRouteQuery) All(ctx context.Context) ([]*PublishedRoute, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PublishedRoute, *PublishedRouteQuery]()
	return withInterceptors[[]*PublishedRoute](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PublishedRouteQuery) AllX(ctx context.Context) []*PublishedRoute {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PublishedRoute IDs.
func (_q *PublishedRouteQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(publishedroute.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PublishedRouteQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PublishedRouteQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PublishedRouteQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PublishedRouteQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PublishedRouteQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PublishedRouteQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PublishedRouteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PublishedRouteQuery) Clone() *PublishedRouteQuery {
	if _q == nil {
		return nil
	}
	return &PublishedRouteQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]publishedroute.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.PublishedRoute{}, _q.predicates...),
		withOwner:  _q.withOwner.Clone(),
		withClient: _q.withClient.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PublishedRouteQuery) WithOwner(opts ...func(*UserQuery)) *PublishedRouteQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOwner = query
	return _q
}

// WithClient tells the query-builder to eager-load the nodes that are connected to
// the "client" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PublishedRouteQuery) WithClient(opts ...func(*TailClientQuery)) *PublishedRouteQuery {
	query := (&TailClientClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withClient = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PublishedRoute.Query().
//		GroupBy(publishedroute.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PublishedRouteQuery) GroupBy(field string, fields ...string) *PublishedRouteGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PublishedRouteGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = publishedroute.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.PublishedRoute.Query().
//		Select(publishedroute.FieldUserID).
//		Scan(ctx, &v)
func (_q *PublishedRouteQuery) Select(fields ...string) *PublishedRouteSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PublishedRouteSelect{PublishedRouteQuery: _q}
	sbuild.label = publishedroute.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PublishedRouteSelect configured with the given aggregations.
func (_q *PublishedRouteQuery) Aggregate(fns ...AggregateFunc) *PublishedRouteSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PublishedRouteQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !publishedroute.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PublishedRouteQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PublishedRoute, error) {
	var (
		nodes       = []*PublishedRoute{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withOwner != nil,
			_q.withClient != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PublishedRoute).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PublishedRoute{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOwner; query != nil {
		if err := _q.loadOwner(ctx, query, nodes, nil,
			func(n *PublishedRoute, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withClient; query != nil {
		if err := _q.loadClient(ctx, query, nodes, nil,
			func(n *PublishedRoute, e *TailClient) { n.Edges.Client = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PublishedRouteQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*PublishedRoute, init func(*PublishedRoute), assign func(*PublishedRoute, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*PublishedRoute)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PublishedRouteQuery) loadClient(ctx context.Context, query *TailClientQuery, nodes []*PublishedRoute, init func(*PublishedRoute), assign func(*PublishedRoute, *TailClient)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*PublishedRoute)
	for i := range nodes {
		fk := nodes[i].ClientID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tailclient.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "client_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PublishedRouteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PublishedRouteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(publishedroute.Table, publishedroute.Columns, sqlgraph.NewFieldSpec(publishedroute.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, publishedroute.FieldID)
		for i := range fields {
			if fields[i] != publishedroute.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withOwner != nil {
			_spec.Node.AddColumnOnce(publishedroute.FieldUserID)
		}
		if _q.withClient != nil {
			_spec.Node.AddColumnOnce(publishedroute.FieldClientID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PublishedRouteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(publishedroute.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = publishedroute.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PublishedRouteGroupBy is the group-by builder for PublishedRoute entities.
type PublishedRouteGroupBy struct {
	selector
	build *PublishedRouteQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PublishedRouteGroupBy) Aggregate(fns ...AggregateFunc) *PublishedRouteGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PublishedRouteGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublishedRouteQuery, *PublishedRouteGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PublishedRouteGroupBy) sqlScan(ctx context.Context, root *PublishedRouteQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PublishedRouteSelect is the builder for selecting fields of PublishedRoute entities.
type PublishedRouteSelect struct {
	*PublishedRouteQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PublishedRouteSelect) Aggregate(fns ...AggregateFunc) *PublishedRouteSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PublishedRouteSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublishedRouteQuery, *PublishedRouteSelect](ctx, _s.PublishedRouteQuery, _s, _s.inters, v)
}

func (_s *PublishedRouteSelect) sqlScan(ctx context.Context, root *PublishedRouteQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
