// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/tailcat-webui/ent/sharefile"
	"github.com/ca-x/tailcat-webui/ent/transfershare"
	"github.com/ca-x/tailcat-webui/ent/user"
)

// ShareFileCreate is the builder for creating a ShareFile entity.
type ShareFileCreate struct {
	config
	mutation *ShareFileMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *ShareFileCreate) SetUserID(v string) *ShareFileCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetShareID sets the "share_id" field.
func (_c *ShareFileCreate) SetShareID(v string) *ShareFileCreate {
	_c.mutation.SetShareID(v)
	return _c
}

// SetStorageName sets the "storage_name" field.
func (_c *ShareFileCreate) SetStorageName(v string) *ShareFileCreate {
	_c.mutation.SetStorageName(v)
	return _c
}

// SetVirtualPath sets the "virtual_path" field.
func (_c *ShareFileCreate) SetVirtualPath(v string) *ShareFileCreate {
	_c.mutation.SetVirtualPath(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *ShareFileCreate) SetSizeBytes(v int64) *ShareFileCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetMtime sets the "mtime" field.
func (_c *ShareFileCreate) SetMtime(v time.Time) *ShareFileCreate {
	_c.mutation.SetMtime(v)
	return _c
}

// SetBlake3 sets the "blake3" field.
func (_c *ShareFileCreate) SetBlake3(v string) *ShareFileCreate {
	_c.mutation.SetBlake3(v)
	return _c
}

// SetBlockSize sets the "block_size" field.
func (_c *ShareFileCreate) SetBlockSize(v int64) *ShareFileCreate {
	_c.mutation.SetBlockSize(v)
	return _c
}

// SetNillableBlockSize sets the "block_size" field if the given value is not nil.
func (_c *ShareFileCreate) SetNillableBlockSize(v *int64) *ShareFileCreate {
	if v != nil {
		_c.SetBlockSize(*v)
	}
	return _c
}

// SetBlockHashes sets the "block_hashes" field.
func (_c *ShareFileCreate) SetBlockHashes(v []string) *ShareFileCreate {
	_c.mutation.SetBlockHashes(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ShareFileCreate) SetCreatedAt(v time.Time) *ShareFileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ShareFileCreate) SetNillableCreatedAt(v *time.Time) *ShareFileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ShareFileCreate) SetID(v string) *ShareFileCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ShareFileCreate) SetNillableID(v *string) *ShareFileCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *ShareFileCreate) SetOwnerID(id string) *ShareFileCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *ShareFileCreate) SetOwner(v *User) *ShareFileCreate {
	return _c.SetOwnerID(v.ID)
}

// SetShare sets the "share" edge to the TransferShare entity.
func (_c *ShareFileCreate) SetShare(v *TransferShare) *ShareFileCreate {
	return _c.SetShareID(v.ID)
}

// Mutation returns the ShareFileMutation object of the builder.
func (_c *ShareFileCreate) Mutation() *ShareFileMutation {
	return _c.mutation
}

// Save creates the ShareFile in the database.
func (_c *ShareFileCreate) Save(ctx context.Context) (*ShareFile, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShareFileCreate) SaveX(ctx context.Context) *ShareFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShareFileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShareFileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShareFileCreate) defaults() error {
	if _, ok := _c.mutation.BlockSize(); !ok {
		v := sharefile.DefaultBlockSize
		_c.mutation.SetBlockSize(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if sharefile.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharefile.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sharefile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if sharefile.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized sharefile.DefaultID (forgotten import ent/runtime?)")
		}
		v := sharefile.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShareFileCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ShareFile.user_id"`)}
	}
	if _, ok := _c.mutation.ShareID(); !ok {
		return &ValidationError{Name: "share_id", err: errors.New(`ent: missing required field "ShareFile.share_id"`)}
	}
	if _, ok := _c.mutation.StorageName(); !ok {
		return &ValidationError{Name: "storage_name", err: errors.New(`ent: missing required field "ShareFile.storage_name"`)}
	}
	if v, ok := _c.mutation.StorageName(); ok {
		if err := sharefile.StorageNameValidator(v); err != nil {
			return &ValidationError{Name: "storage_name", err: fmt.Errorf(`ent: validator failed for field "ShareFile.storage_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VirtualPath(); !ok {
		return &ValidationError{Name: "virtual_path", err: errors.New(`ent: missing required field "ShareFile.virtual_path"`)}
	}
	if v, ok := _c.mutation.VirtualPath(); ok {
		if err := sharefile.VirtualPathValidator(v); err != nil {
			return &ValidationError{Name: "virtual_path", err: fmt.Errorf(`ent: validator failed for field "ShareFile.virtual_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "ShareFile.size_bytes"`)}
	}
	if v, ok := _c.mutation.SizeBytes(); ok {
		if err := sharefile.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "ShareFile.size_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mtime(); !ok {
		return &ValidationError{Name: "mtime", err: errors.New(`ent: missing required field "ShareFile.mtime"`)}
	}
	if _, ok := _c.mutation.Blake3(); !ok {
		return &ValidationError{Name: "blake3", err: errors.New(`ent: missing required field "ShareFile.blake3"`)}
	}
	if v, ok := _c.mutation.Blake3(); ok {
		if err := sharefile.Blake3Validator(v); err != nil {
			return &ValidationError{Name: "blake3", err: fmt.Errorf(`ent: validator failed for field "ShareFile.blake3": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BlockSize(); !ok {
		return &ValidationError{Name: "block_size", err: errors.New(`ent: missing required field "ShareFile.block_size"`)}
	}
	if v, ok := _c.mutation.BlockSize(); ok {
		if err := sharefile.BlockSizeValidator(v); err != nil {
			return &ValidationError{Name: "block_size", err: fmt.Errorf(`ent: validator failed for field "ShareFile.block_size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BlockHashes(); !ok {
		return &ValidationError{Name: "block_hashes", err: errors.New(`ent: missing required field "ShareFile.block_hashes"`)}
	}
	if v, ok := _c.mutation.BlockHashes(); ok {
		if err := sharefile.BlockHashesValidator(v); err != nil {
			return &ValidationError{Name: "block_hashes", err: fmt.Errorf(`ent: validator failed for field "ShareFile.block_hashes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ShareFile.created_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "ShareFile.owner"`)}
	}
	if len(_c.mutation.ShareIDs()) == 0 {
		return &ValidationError{Name: "share", err: errors.New(`ent: missing required edge "ShareFile.share"`)}
	}
	return nil
}

func (_c *ShareFileCreate) sqlSave(ctx context.Context) (*ShareFile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ShareFile.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShareFileCreate) createSpec() (*ShareFile, *sqlgraph.CreateSpec) {
	var (
		_node = &ShareFile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sharefile.Table, sqlgraph.NewFieldSpec(sharefile.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.StorageName(); ok {
		_spec.SetField(sharefile.FieldStorageName, field.TypeString, value)
		_node.StorageName = value
	}
	if value, ok := _c.mutation.VirtualPath(); ok {
		_spec.SetField(sharefile.FieldVirtualPath, field.TypeString, value)
		_node.VirtualPath = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(sharefile.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.Mtime(); ok {
		_spec.SetField(sharefile.FieldMtime, field.TypeTime, value)
		_node.Mtime = value
	}
	if value, ok := _c.mutation.Blake3(); ok {
		_spec.SetField(sharefile.FieldBlake3, field.TypeString, value)
		_node.Blake3 = value
	}
	if value, ok := _c.mutation.BlockSize(); ok {
		_spec.SetField(sharefile.FieldBlockSize, field.TypeInt64, value)
		_node.BlockSize = value
	}
	if value, ok := _c.mutation.BlockHashes(); ok {
		_spec.SetField(sharefile.FieldBlockHashes, field.TypeJSON, value)
		_node.BlockHashes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sharefile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharefile.OwnerTable,
			Columns: []string{sharefile.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ShareIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharefile.ShareTable,
			Columns: []string{sharefile.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transfershare.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ShareID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ShareFileCreateBulk is the builder for creating many ShareFile entities in bulk.
type ShareFileCreateBulk struct {
	config
	err      error
	builders []*ShareFileCreate
}

// Save creates the ShareFile entities in the database.
func (_c *ShareFileCreateBulk) Save(ctx context.Context) ([]*ShareFile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ShareFile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShareFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShareFileCreateBulk) SaveX(ctx context.Context) []*ShareFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShareFileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShareFileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
