// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/tailcat-webui/ent/diagnosticrun"
	"github.com/ca-x/tailcat-webui/ent/publishedroute"
	"github.com/ca-x/tailcat-webui/ent/tailclient"
	"github.com/ca-x/tailcat-webui/ent/user"
)

// TailClientCreate is the builder for creating a TailClient entity.
type TailClientCreate struct {
	config
	mutation *TailClientMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *TailClientCreate) SetUserID(v string) *TailClientCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *TailClientCreate) SetName(v string) *TailClientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetServerTokenCipher sets the "server_token_cipher" field.
func (_c *TailClientCreate) SetServerTokenCipher(v []byte) *TailClientCreate {
	_c.mutation.SetServerTokenCipher(v)
	return _c
}

// SetTokenHint sets the "token_hint" field.
func (_c *TailClientCreate) SetTokenHint(v string) *TailClientCreate {
	_c.mutation.SetTokenHint(v)
	return _c
}

// SetKeyCipher sets the "key_cipher" field.
func (_c *TailClientCreate) SetKeyCipher(v []byte) *TailClientCreate {
	_c.mutation.SetKeyCipher(v)
	return _c
}

// SetDerpMapURL sets the "derp_map_url" field.
func (_c *TailClientCreate) SetDerpMapURL(v string) *TailClientCreate {
	_c.mutation.SetDerpMapURL(v)
	return _c
}

// SetNillableDerpMapURL sets the "derp_map_url" field if the given value is not nil.
func (_c *TailClientCreate) SetNillableDerpMapURL(v *string) *TailClientCreate {
	if v != nil {
		_c.SetDerpMapURL(*v)
	}
	return _c
}

// SetLastPingMs sets the "last_ping_ms" field.
func (_c *TailClientCreate) SetLastPingMs(v int64) *TailClientCreate {
	_c.mutation.SetLastPingMs(v)
	return _c
}

// SetNillableLastPingMs sets the "last_ping_ms" field if the given value is not nil.
func (_c *TailClientCreate) SetNillableLastPingMs(v *int64) *TailClientCreate {
	if v != nil {
		_c.SetLastPingMs(*v)
	}
	return _c
}

// SetLastPath sets the "last_path" field.
func (_c *TailClientCreate) SetLastPath(v string) *TailClientCreate {
	_c.mutation.SetLastPath(v)
	return _c
}

// SetNillableLastPath sets the "last_path" field if the given value is not nil.
func (_c *TailClientCreate) SetNillableLastPath(v *string) *TailClientCreate {
	if v != nil {
		_c.SetLastPath(*v)
	}
	return _c
}

// SetLastPingAt sets the "last_ping_at" field.
func (_c *TailClientCreate) SetLastPingAt(v time.Time) *TailClientCreate {
	_c.mutation.SetLastPingAt(v)
	return _c
}

// SetNillableLastPingAt sets the "last_ping_at" field if the given value is not nil.
func (_c *TailClientCreate) SetNillableLastPingAt(v *time.Time) *TailClientCreate {
	if v != nil {
		_c.SetLastPingAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TailClientCreate) SetCreatedAt(v time.Time) *TailClientCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TailClientCreate) SetNillableCreatedAt(v *time.Time) *TailClientCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TailClientCreate) SetUpdatedAt(v time.Time) *TailClientCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TailClientCreate) SetNillableUpdatedAt(v *time.Time) *TailClientCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TailClientCreate) SetID(v string) *TailClientCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TailClientCreate) SetNillableID(v *string) *TailClientCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *TailClientCreate) SetOwnerID(id string) *TailClientCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *TailClientCreate) SetOwner(v *User) *TailClientCreate {
	return _c.SetOwnerID(v.ID)
}

// AddDiagnosticRunIDs adds the "diagnostic_runs" edge to the DiagnosticRun entity by IDs.
func (_c *TailClientCreate) AddDiagnosticRunIDs(ids ...string) *TailClientCreate {
	_c.mutation.AddDiagnosticRunIDs(ids...)
	return _c
}

// AddDiagnosticRuns adds the "diagnostic_runs" edges to the DiagnosticRun entity.
func (_c *TailClientCreate) AddDiagnosticRuns(v ...*DiagnosticRun) *TailClientCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDiagnosticRunIDs(ids...)
}

// AddRouteIDs adds the "routes" edge to the PublishedRoute entity by IDs.
func (_c *TailClientCreate) AddRouteIDs(ids ...string) *TailClientCreate {
	_c.mutation.AddRouteIDs(ids...)
	return _c
}

// AddRoutes adds the "routes" edges to the PublishedRoute entity.
func (_c *TailClientCreate) AddRoutes(v ...*PublishedRoute) *TailClientCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRouteIDs(ids...)
}

// Mutation returns the TailClientMutation object of the builder.
func (_c *TailClientCreate) Mutation() *TailClientMutation {
	return _c.mutation
}

// Save creates the TailClient in the database.
func (_c *TailClientCreate) Save(ctx context.Context) (*TailClient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TailClientCreate) SaveX(ctx context.Context) *TailClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TailClientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TailClientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TailClientCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tailclient.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tailclient.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := tailclient.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TailClientCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TailClient.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TailClient.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := tailclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TailClient.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ServerTokenCipher(); !ok {
		return &ValidationError{Name: "server_token_cipher", err: errors.New(`ent: missing required field "TailClient.server_token_cipher"`)}
	}
	if v, ok := _c.mutation.ServerTokenCipher(); ok {
		if err := tailclient.ServerTokenCipherValidator(v); err != nil {
			return &ValidationError{Name: "server_token_cipher", err: fmt.Errorf(`ent: validator failed for field "TailClient.server_token_cipher": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHint(); !ok {
		return &ValidationError{Name: "token_hint", err: errors.New(`ent: missing required field "TailClient.token_hint"`)}
	}
	if v, ok := _c.mutation.TokenHint(); ok {
		if err := tailclient.TokenHintValidator(v); err != nil {
			return &ValidationError{Name: "token_hint", err: fmt.Errorf(`ent: validator failed for field "TailClient.token_hint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TailClient.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TailClient.updated_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "TailClient.owner"`)}
	}
	return nil
}

func (_c *TailClientCreate) sqlSave(ctx context.Context) (*TailClient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TailClient.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TailClientCreate) createSpec() (*TailClient, *sqlgraph.CreateSpec) {
	var (
		_node = &TailClient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tailclient.Table, sqlgraph.NewFieldSpec(tailclient.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tailclient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ServerTokenCipher(); ok {
		_spec.SetField(tailclient.FieldServerTokenCipher, field.TypeBytes, value)
		_node.ServerTokenCipher = value
	}
	if value, ok := _c.mutation.TokenHint(); ok {
		_spec.SetField(tailclient.FieldTokenHint, field.TypeString, value)
		_node.TokenHint = value
	}
	if value, ok := _c.mutation.KeyCipher(); ok {
		_spec.SetField(tailclient.FieldKeyCipher, field.TypeBytes, value)
		_node.KeyCipher = value
	}
	if value, ok := _c.mutation.DerpMapURL(); ok {
		_spec.SetField(tailclient.FieldDerpMapURL, field.TypeString, value)
		_node.DerpMapURL = value
	}
	if value, ok := _c.mutation.LastPingMs(); ok {
		_spec.SetField(tailclient.FieldLastPingMs, field.TypeInt64, value)
		_node.LastPingMs = &value
	}
	if value, ok := _c.mutation.LastPath(); ok {
		_spec.SetField(tailclient.FieldLastPath, field.TypeString, value)
		_node.LastPath = value
	}
	if value, ok := _c.mutation.LastPingAt(); ok {
		_spec.SetField(tailclient.FieldLastPingAt, field.TypeTime, value)
		_node.LastPingAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tailclient.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tailclient.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tailclient.OwnerTable,
			Columns: []string{tailclient.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DiagnosticRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.DiagnosticRunsTable,
			Columns: []string{tailclient.DiagnosticRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagnosticrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.RoutesTable,
			Columns: []string{tailclient.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publishedroute.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TailClientCreateBulk is the builder for creating many TailClient entities in bulk.
type TailClientCreateBulk struct {
	config
	err      error
	builders []*TailClientCreate
}

// Save creates the TailClient entities in the database.
func (_c *TailClientCreateBulk) Save(ctx context.Context) ([]*TailClient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TailClient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TailClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TailClientCreateBulk) SaveX(ctx context.Context) []*TailClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TailClientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TailClientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
