// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/tailcat-webui/ent/diagnosticrun"
	"github.com/ca-x/tailcat-webui/ent/predicate"
	"github.com/ca-x/tailcat-webui/ent/publishedroute"
	"github.com/ca-x/tailcat-webui/ent/tailclient"
	"github.com/ca-x/tailcat-webui/ent/transferjob"
	"github.com/ca-x/tailcat-webui/ent/user"
)

// TailClientQuery is the builder for querying TailClient entities.
type TailClientQuery struct {
	config
	ctx                *QueryContext
	order              []tailclient.OrderOption
	inters             []Interceptor
	predicates         []predicate.TailClient
	withOwner          *UserQuery
	withDiagnosticRuns *DiagnosticRunQuery
	withRoutes         *PublishedRouteQuery
	withTransferJobs   *TransferJobQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TailClientQuery builder.
func (_q *TailClientQuery) Where(ps ...predicate.TailClient) *TailClientQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TailClientQuery) Limit(limit int) *TailClientQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TailClientQuery) Offset(offset int) *TailClientQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TailClientQuery) Unique(unique bool) *TailClientQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TailClientQuery) Order(o ...tailclient.OrderOption) *TailClientQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOwner chains the current query on the "owner" edge.
func (_q *TailClientQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tailclient.Table, tailclient.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tailclient.OwnerTable, tailclient.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDiagnosticRuns chains the current query on the "diagnostic_runs" edge.
func (_q *TailClientQuery) QueryDiagnosticRuns() *DiagnosticRunQuery {
	query := (&DiagnosticRunClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tailclient.Table, tailclient.FieldID, selector),
			sqlgraph.To(diagnosticrun.Table, diagnosticrun.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tailclient.DiagnosticRunsTable, tailclient.DiagnosticRunsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoutes chains the current query on the "routes" edge.
func (_q *TailClientQuery) QueryRoutes() *PublishedRouteQuery {
	query := (&PublishedRouteClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tailclient.Table, tailclient.FieldID, selector),
			sqlgraph.To(publishedroute.Table, publishedroute.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tailclient.RoutesTable, tailclient.RoutesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTransferJobs chains the current query on the "transfer_jobs" edge.
func (_q *TailClientQuery) QueryTransferJobs() *TransferJobQuery {
	query := (&TransferJobClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tailclient.Table, tailclient.FieldID, selector),
			sqlgraph.To(transferjob.Table, transferjob.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tailclient.TransferJobsTable, tailclient.TransferJobsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TailClient entity from the query.
// Returns a *NotFoundError when no TailClient was found.
func (_q *TailClientQuery) First(ctx context.Context) (*TailClient, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tailclient.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TailClientQuery) FirstX(ctx context.Context) *TailClient {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TailClient ID from the query.
// Returns a *NotFoundError when no TailClient ID was found.
func (_q *TailClientQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tailclient.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TailClientQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TailClient entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TailClient entity is found.
// Returns a *NotFoundError when no TailClient entities are found.
func (_q *TailClientQuery) Only(ctx context.Context) (*TailClient, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tailclient.Label}
	default:
		return nil, &NotSingularError{tailclient.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TailClientQuery) OnlyX(ctx context.Context) *TailClient {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TailClient ID in the query.
// Returns a *NotSingularError when more than one TailClient ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TailClientQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tailclient.Label}
	default:
		err = &NotSingularError{tailclient.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TailClientQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TailClients.
func (_q *TailClientQuery) All(ctx context.Context) ([]*TailClient, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TailClient, *TailClientQuery]()
	return withInterceptors[[]*TailClient](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TailClientQuery) AllX(ctx context.Context) []*TailClient {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TailClient IDs.
func (_q *TailClientQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(tailclient.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TailClientQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TailClientQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TailClientQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TailClientQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TailClientQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TailClientQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TailClientQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TailClientQuery) Clone() *TailClientQuery {
	if _q == nil {
		return nil
	}
	return &TailClientQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]tailclient.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.TailClient{}, _q.predicates...),
		withOwner:          _q.withOwner.Clone(),
		withDiagnosticRuns: _q.withDiagnosticRuns.Clone(),
		withRoutes:         _q.withRoutes.Clone(),
		withTransferJobs:   _q.withTransferJobs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TailClientQuery) WithOwner(opts ...func(*UserQuery)) *TailClientQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOwner = query
	return _q
}

// WithDiagnosticRuns tells the query-builder to eager-load the nodes that are connected to
// the "diagnostic_runs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TailClientQuery) WithDiagnosticRuns(opts ...func(*DiagnosticRunQuery)) *TailClientQuery {
	query := (&DiagnosticRunClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDiagnosticRuns = query
	return _q
}

// WithRoutes tells the query-builder to eager-load the nodes that are connected to
// the "routes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TailClientQuery) WithRoutes(opts ...func(*PublishedRouteQuery)) *TailClientQuery {
	query := (&PublishedRouteClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRoutes = query
	return _q
}

// WithTransferJobs tells the query-builder to eager-load the nodes that are connected to
// the "transfer_jobs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TailClientQuery) WithTransferJobs(opts ...func(*TransferJobQuery)) *TailClientQuery {
	query := (&TransferJobClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTransferJobs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TailClient.Query().
//		GroupBy(tailclient.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *TailClientQuery) GroupBy(field string, fields ...string) *TailClientGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TailClientGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = tailclient.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.TailClient.Query().
//		Select(tailclient.FieldUserID).
//		Scan(ctx, &v)
func (_q *TailClientQuery) Select(fields ...string) *TailClientSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TailClientSelect{TailClientQuery: _q}
	sbuild.label = tailclient.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TailClientSelect configured with the given aggregations.
func (_q *TailClientQuery) Aggregate(fns ...AggregateFunc) *TailClientSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TailClientQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !tailclient.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TailClientQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TailClient, error) {
	var (
		nodes       = []*TailClient{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withOwner != nil,
			_q.withDiagnosticRuns != nil,
			_q.withRoutes != nil,
			_q.withTransferJobs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TailClient).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TailClient{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOwner; query != nil {
		if err := _q.loadOwner(ctx, query, nodes, nil,
			func(n *TailClient, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDiagnosticRuns; query != nil {
		if err := _q.loadDiagnosticRuns(ctx, query, nodes,
			func(n *TailClient) { n.Edges.DiagnosticRuns = []*DiagnosticRun{} },
			func(n *TailClient, e *DiagnosticRun) { n.Edges.DiagnosticRuns = append(n.Edges.DiagnosticRuns, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRoutes; query != nil {
		if err := _q.loadRoutes(ctx, query, nodes,
			func(n *TailClient) { n.Edges.Routes = []*PublishedRoute{} },
			func(n *TailClient, e *PublishedRoute) { n.Edges.Routes = append(n.Edges.Routes, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTransferJobs; query != nil {
		if err := _q.loadTransferJobs(ctx, query, nodes,
			func(n *TailClient) { n.Edges.TransferJobs = []*TransferJob{} },
			func(n *TailClient, e *TransferJob) { n.Edges.TransferJobs = append(n.Edges.TransferJobs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TailClientQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*TailClient, init func(*TailClient), assign func(*TailClient, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*TailClient)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *TailClientQuery) loadDiagnosticRuns(ctx context.Context, query *DiagnosticRunQuery, nodes []*TailClient, init func(*TailClient), assign func(*TailClient, *DiagnosticRun)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*TailClient)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(diagnosticrun.FieldClientID)
	}
	query.Where(predicate.DiagnosticRun(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tailclient.DiagnosticRunsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ClientID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "client_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TailClientQuery) loadRoutes(ctx context.Context, query *PublishedRouteQuery, nodes []*TailClient, init func(*TailClient), assign func(*TailClient, *PublishedRoute)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*TailClient)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(publishedroute.FieldClientID)
	}
	query.Where(predicate.PublishedRoute(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tailclient.RoutesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ClientID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "client_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TailClientQuery) loadTransferJobs(ctx context.Context, query *TransferJobQuery, nodes []*TailClient, init func(*TailClient), assign func(*TailClient, *TransferJob)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*TailClient)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(transferjob.FieldClientID)
	}
	query.Where(predicate.TransferJob(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tailclient.TransferJobsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ClientID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "client_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *TailClientQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TailClientQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tailclient.Table, tailclient.Columns, sqlgraph.NewFieldSpec(tailclient.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tailclient.FieldID)
		for i := range fields {
			if fields[i] != tailclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withOwner != nil {
			_spec.Node.AddColumnOnce(tailclient.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TailClientQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(tailclient.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = tailclient.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TailClientGroupBy is the group-by builder for TailClient entities.
type TailClientGroupBy struct {
	selector
	build *TailClientQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TailClientGroupBy) Aggregate(fns ...AggregateFunc) *TailClientGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TailClientGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TailClientQuery, *TailClientGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TailClientGroupBy) sqlScan(ctx context.Context, root *TailClientQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TailClientSelect is the builder for selecting fields of TailClient entities.
type TailClientSelect struct {
	*TailClientQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TailClientSelect) Aggregate(fns ...AggregateFunc) *TailClientSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TailClientSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TailClientQuery, *TailClientSelect](ctx, _s.TailClientQuery, _s, _s.inters, v)
}

func (_s *TailClientSelect) sqlScan(ctx context.Context, root *TailClientQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
