// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/tailcat-webui/ent/diagnosticrun"
	"github.com/ca-x/tailcat-webui/ent/predicate"
	"github.com/ca-x/tailcat-webui/ent/publishedroute"
	"github.com/ca-x/tailcat-webui/ent/tailclient"
	"github.com/ca-x/tailcat-webui/ent/transferjob"
)

// TailClientUpdate is the builder for updating TailClient entities.
type TailClientUpdate struct {
	config
	hooks    []Hook
	mutation *TailClientMutation
}

// Where appends a list predicates to the TailClientUpdate builder.
func (_u *TailClientUpdate) Where(ps ...predicate.TailClient) *TailClientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TailClientUpdate) SetName(v string) *TailClientUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TailClientUpdate) SetNillableName(v *string) *TailClientUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetServerTokenCipher sets the "server_token_cipher" field.
func (_u *TailClientUpdate) SetServerTokenCipher(v []byte) *TailClientUpdate {
	_u.mutation.SetServerTokenCipher(v)
	return _u
}

// SetTokenHint sets the "token_hint" field.
func (_u *TailClientUpdate) SetTokenHint(v string) *TailClientUpdate {
	_u.mutation.SetTokenHint(v)
	return _u
}

// SetNillableTokenHint sets the "token_hint" field if the given value is not nil.
func (_u *TailClientUpdate) SetNillableTokenHint(v *string) *TailClientUpdate {
	if v != nil {
		_u.SetTokenHint(*v)
	}
	return _u
}

// SetKeyCipher sets the "key_cipher" field.
func (_u *TailClientUpdate) SetKeyCipher(v []byte) *TailClientUpdate {
	_u.mutation.SetKeyCipher(v)
	return _u
}

// ClearKeyCipher clears the value of the "key_cipher" field.
func (_u *TailClientUpdate) ClearKeyCipher() *TailClientUpdate {
	_u.mutation.ClearKeyCipher()
	return _u
}

// SetDerpMapURL sets the "derp_map_url" field.
func (_u *TailClientUpdate) SetDerpMapURL(v string) *TailClientUpdate {
	_u.mutation.SetDerpMapURL(v)
	return _u
}

// SetNillableDerpMapURL sets the "derp_map_url" field if the given value is not nil.
func (_u *TailClientUpdate) SetNillableDerpMapURL(v *string) *TailClientUpdate {
	if v != nil {
		_u.SetDerpMapURL(*v)
	}
	return _u
}

// ClearDerpMapURL clears the value of the "derp_map_url" field.
func (_u *TailClientUpdate) ClearDerpMapURL() *TailClientUpdate {
	_u.mutation.ClearDerpMapURL()
	return _u
}

// SetLastPingMs sets the "last_ping_ms" field.
func (_u *TailClientUpdate) SetLastPingMs(v int64) *TailClientUpdate {
	_u.mutation.ResetLastPingMs()
	_u.mutation.SetLastPingMs(v)
	return _u
}

// SetNillableLastPingMs sets the "last_ping_ms" field if the given value is not nil.
func (_u *TailClientUpdate) SetNillableLastPingMs(v *int64) *TailClientUpdate {
	if v != nil {
		_u.SetLastPingMs(*v)
	}
	return _u
}

// AddLastPingMs adds value to the "last_ping_ms" field.
func (_u *TailClientUpdate) AddLastPingMs(v int64) *TailClientUpdate {
	_u.mutation.AddLastPingMs(v)
	return _u
}

// ClearLastPingMs clears the value of the "last_ping_ms" field.
func (_u *TailClientUpdate) ClearLastPingMs() *TailClientUpdate {
	_u.mutation.ClearLastPingMs()
	return _u
}

// SetLastPath sets the "last_path" field.
func (_u *TailClientUpdate) SetLastPath(v string) *TailClientUpdate {
	_u.mutation.SetLastPath(v)
	return _u
}

// SetNillableLastPath sets the "last_path" field if the given value is not nil.
func (_u *TailClientUpdate) SetNillableLastPath(v *string) *TailClientUpdate {
	if v != nil {
		_u.SetLastPath(*v)
	}
	return _u
}

// ClearLastPath clears the value of the "last_path" field.
func (_u *TailClientUpdate) ClearLastPath() *TailClientUpdate {
	_u.mutation.ClearLastPath()
	return _u
}

// SetLastPingAt sets the "last_ping_at" field.
func (_u *TailClientUpdate) SetLastPingAt(v time.Time) *TailClientUpdate {
	_u.mutation.SetLastPingAt(v)
	return _u
}

// SetNillableLastPingAt sets the "last_ping_at" field if the given value is not nil.
func (_u *TailClientUpdate) SetNillableLastPingAt(v *time.Time) *TailClientUpdate {
	if v != nil {
		_u.SetLastPingAt(*v)
	}
	return _u
}

// ClearLastPingAt clears the value of the "last_ping_at" field.
func (_u *TailClientUpdate) ClearLastPingAt() *TailClientUpdate {
	_u.mutation.ClearLastPingAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TailClientUpdate) SetUpdatedAt(v time.Time) *TailClientUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddDiagnosticRunIDs adds the "diagnostic_runs" edge to the DiagnosticRun entity by IDs.
func (_u *TailClientUpdate) AddDiagnosticRunIDs(ids ...string) *TailClientUpdate {
	_u.mutation.AddDiagnosticRunIDs(ids...)
	return _u
}

// AddDiagnosticRuns adds the "diagnostic_runs" edges to the DiagnosticRun entity.
func (_u *TailClientUpdate) AddDiagnosticRuns(v ...*DiagnosticRun) *TailClientUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDiagnosticRunIDs(ids...)
}

// AddRouteIDs adds the "routes" edge to the PublishedRoute entity by IDs.
func (_u *TailClientUpdate) AddRouteIDs(ids ...string) *TailClientUpdate {
	_u.mutation.AddRouteIDs(ids...)
	return _u
}

// AddRoutes adds the "routes" edges to the PublishedRoute entity.
func (_u *TailClientUpdate) AddRoutes(v ...*PublishedRoute) *TailClientUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRouteIDs(ids...)
}

// AddTransferJobIDs adds the "transfer_jobs" edge to the TransferJob entity by IDs.
func (_u *TailClientUpdate) AddTransferJobIDs(ids ...string) *TailClientUpdate {
	_u.mutation.AddTransferJobIDs(ids...)
	return _u
}

// AddTransferJobs adds the "transfer_jobs" edges to the TransferJob entity.
func (_u *TailClientUpdate) AddTransferJobs(v ...*TransferJob) *TailClientUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransferJobIDs(ids...)
}

// Mutation returns the TailClientMutation object of the builder.
func (_u *TailClientUpdate) Mutation() *TailClientMutation {
	return _u.mutation
}

// ClearDiagnosticRuns clears all "diagnostic_runs" edges to the DiagnosticRun entity.
func (_u *TailClientUpdate) ClearDiagnosticRuns() *TailClientUpdate {
	_u.mutation.ClearDiagnosticRuns()
	return _u
}

// RemoveDiagnosticRunIDs removes the "diagnostic_runs" edge to DiagnosticRun entities by IDs.
func (_u *TailClientUpdate) RemoveDiagnosticRunIDs(ids ...string) *TailClientUpdate {
	_u.mutation.RemoveDiagnosticRunIDs(ids...)
	return _u
}

// RemoveDiagnosticRuns removes "diagnostic_runs" edges to DiagnosticRun entities.
func (_u *TailClientUpdate) RemoveDiagnosticRuns(v ...*DiagnosticRun) *TailClientUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDiagnosticRunIDs(ids...)
}

// ClearRoutes clears all "routes" edges to the PublishedRoute entity.
func (_u *TailClientUpdate) ClearRoutes() *TailClientUpdate {
	_u.mutation.ClearRoutes()
	return _u
}

// RemoveRouteIDs removes the "routes" edge to PublishedRoute entities by IDs.
func (_u *TailClientUpdate) RemoveRouteIDs(ids ...string) *TailClientUpdate {
	_u.mutation.RemoveRouteIDs(ids...)
	return _u
}

// RemoveRoutes removes "routes" edges to PublishedRoute entities.
func (_u *TailClientUpdate) RemoveRoutes(v ...*PublishedRoute) *TailClientUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRouteIDs(ids...)
}

// ClearTransferJobs clears all "transfer_jobs" edges to the TransferJob entity.
func (_u *TailClientUpdate) ClearTransferJobs() *TailClientUpdate {
	_u.mutation.ClearTransferJobs()
	return _u
}

// RemoveTransferJobIDs removes the "transfer_jobs" edge to TransferJob entities by IDs.
func (_u *TailClientUpdate) RemoveTransferJobIDs(ids ...string) *TailClientUpdate {
	_u.mutation.RemoveTransferJobIDs(ids...)
	return _u
}

// RemoveTransferJobs removes "transfer_jobs" edges to TransferJob entities.
func (_u *TailClientUpdate) RemoveTransferJobs(v ...*TransferJob) *TailClientUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransferJobIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TailClientUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TailClientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TailClientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TailClientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TailClientUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tailclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TailClientUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tailclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TailClient.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServerTokenCipher(); ok {
		if err := tailclient.ServerTokenCipherValidator(v); err != nil {
			return &ValidationError{Name: "server_token_cipher", err: fmt.Errorf(`ent: validator failed for field "TailClient.server_token_cipher": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHint(); ok {
		if err := tailclient.TokenHintValidator(v); err != nil {
			return &ValidationError{Name: "token_hint", err: fmt.Errorf(`ent: validator failed for field "TailClient.token_hint": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TailClient.owner"`)
	}
	return nil
}

func (_u *TailClientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tailclient.Table, tailclient.Columns, sqlgraph.NewFieldSpec(tailclient.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tailclient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServerTokenCipher(); ok {
		_spec.SetField(tailclient.FieldServerTokenCipher, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.TokenHint(); ok {
		_spec.SetField(tailclient.FieldTokenHint, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyCipher(); ok {
		_spec.SetField(tailclient.FieldKeyCipher, field.TypeBytes, value)
	}
	if _u.mutation.KeyCipherCleared() {
		_spec.ClearField(tailclient.FieldKeyCipher, field.TypeBytes)
	}
	if value, ok := _u.mutation.DerpMapURL(); ok {
		_spec.SetField(tailclient.FieldDerpMapURL, field.TypeString, value)
	}
	if _u.mutation.DerpMapURLCleared() {
		_spec.ClearField(tailclient.FieldDerpMapURL, field.TypeString)
	}
	if value, ok := _u.mutation.LastPingMs(); ok {
		_spec.SetField(tailclient.FieldLastPingMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastPingMs(); ok {
		_spec.AddField(tailclient.FieldLastPingMs, field.TypeInt64, value)
	}
	if _u.mutation.LastPingMsCleared() {
		_spec.ClearField(tailclient.FieldLastPingMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastPath(); ok {
		_spec.SetField(tailclient.FieldLastPath, field.TypeString, value)
	}
	if _u.mutation.LastPathCleared() {
		_spec.ClearField(tailclient.FieldLastPath, field.TypeString)
	}
	if value, ok := _u.mutation.LastPingAt(); ok {
		_spec.SetField(tailclient.FieldLastPingAt, field.TypeTime, value)
	}
	if _u.mutation.LastPingAtCleared() {
		_spec.ClearField(tailclient.FieldLastPingAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tailclient.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.DiagnosticRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.DiagnosticRunsTable,
			Columns: []string{tailclient.DiagnosticRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagnosticrun.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDiagnosticRunsIDs(); len(nodes) > 0 && !_u.mutation.DiagnosticRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.DiagnosticRunsTable,
			Columns: []string{tailclient.DiagnosticRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagnosticrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DiagnosticRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.DiagnosticRunsTable,
			Columns: []string{tailclient.DiagnosticRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagnosticrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.RoutesTable,
			Columns: []string{tailclient.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publishedroute.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoutesIDs(); len(nodes) > 0 && !_u.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.RoutesTable,
			Columns: []string{tailclient.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publishedroute.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.RoutesTable,
			Columns: []string{tailclient.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publishedroute.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransferJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.TransferJobsTable,
			Columns: []string{tailclient.TransferJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferjob.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransferJobsIDs(); len(nodes) > 0 && !_u.mutation.TransferJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.TransferJobsTable,
			Columns: []string{tailclient.TransferJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransferJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.TransferJobsTable,
			Columns: []string{tailclient.TransferJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tailclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TailClientUpdateOne is the builder for updating a single TailClient entity.
type TailClientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TailClientMutation
}

// SetName sets the "name" field.
func (_u *TailClientUpdateOne) SetName(v string) *TailClientUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TailClientUpdateOne) SetNillableName(v *string) *TailClientUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetServerTokenCipher sets the "server_token_cipher" field.
func (_u *TailClientUpdateOne) SetServerTokenCipher(v []byte) *TailClientUpdateOne {
	_u.mutation.SetServerTokenCipher(v)
	return _u
}

// SetTokenHint sets the "token_hint" field.
func (_u *TailClientUpdateOne) SetTokenHint(v string) *TailClientUpdateOne {
	_u.mutation.SetTokenHint(v)
	return _u
}

// SetNillableTokenHint sets the "token_hint" field if the given value is not nil.
func (_u *TailClientUpdateOne) SetNillableTokenHint(v *string) *TailClientUpdateOne {
	if v != nil {
		_u.SetTokenHint(*v)
	}
	return _u
}

// SetKeyCipher sets the "key_cipher" field.
func (_u *TailClientUpdateOne) SetKeyCipher(v []byte) *TailClientUpdateOne {
	_u.mutation.SetKeyCipher(v)
	return _u
}

// ClearKeyCipher clears the value of the "key_cipher" field.
func (_u *TailClientUpdateOne) ClearKeyCipher() *TailClientUpdateOne {
	_u.mutation.ClearKeyCipher()
	return _u
}

// SetDerpMapURL sets the "derp_map_url" field.
func (_u *TailClientUpdateOne) SetDerpMapURL(v string) *TailClientUpdateOne {
	_u.mutation.SetDerpMapURL(v)
	return _u
}

// SetNillableDerpMapURL sets the "derp_map_url" field if the given value is not nil.
func (_u *TailClientUpdateOne) SetNillableDerpMapURL(v *string) *TailClientUpdateOne {
	if v != nil {
		_u.SetDerpMapURL(*v)
	}
	return _u
}

// ClearDerpMapURL clears the value of the "derp_map_url" field.
func (_u *TailClientUpdateOne) ClearDerpMapURL() *TailClientUpdateOne {
	_u.mutation.ClearDerpMapURL()
	return _u
}

// SetLastPingMs sets the "last_ping_ms" field.
func (_u *TailClientUpdateOne) SetLastPingMs(v int64) *TailClientUpdateOne {
	_u.mutation.ResetLastPingMs()
	_u.mutation.SetLastPingMs(v)
	return _u
}

// SetNillableLastPingMs sets the "last_ping_ms" field if the given value is not nil.
func (_u *TailClientUpdateOne) SetNillableLastPingMs(v *int64) *TailClientUpdateOne {
	if v != nil {
		_u.SetLastPingMs(*v)
	}
	return _u
}

// AddLastPingMs adds value to the "last_ping_ms" field.
func (_u *TailClientUpdateOne) AddLastPingMs(v int64) *TailClientUpdateOne {
	_u.mutation.AddLastPingMs(v)
	return _u
}

// ClearLastPingMs clears the value of the "last_ping_ms" field.
func (_u *TailClientUpdateOne) ClearLastPingMs() *TailClientUpdateOne {
	_u.mutation.ClearLastPingMs()
	return _u
}

// SetLastPath sets the "last_path" field.
func (_u *TailClientUpdateOne) SetLastPath(v string) *TailClientUpdateOne {
	_u.mutation.SetLastPath(v)
	return _u
}

// SetNillableLastPath sets the "last_path" field if the given value is not nil.
func (_u *TailClientUpdateOne) SetNillableLastPath(v *string) *TailClientUpdateOne {
	if v != nil {
		_u.SetLastPath(*v)
	}
	return _u
}

// ClearLastPath clears the value of the "last_path" field.
func (_u *TailClientUpdateOne) ClearLastPath() *TailClientUpdateOne {
	_u.mutation.ClearLastPath()
	return _u
}

// SetLastPingAt sets the "last_ping_at" field.
func (_u *TailClientUpdateOne) SetLastPingAt(v time.Time) *TailClientUpdateOne {
	_u.mutation.SetLastPingAt(v)
	return _u
}

// SetNillableLastPingAt sets the "last_ping_at" field if the given value is not nil.
func (_u *TailClientUpdateOne) SetNillableLastPingAt(v *time.Time) *TailClientUpdateOne {
	if v != nil {
		_u.SetLastPingAt(*v)
	}
	return _u
}

// ClearLastPingAt clears the value of the "last_ping_at" field.
func (_u *TailClientUpdateOne) ClearLastPingAt() *TailClientUpdateOne {
	_u.mutation.ClearLastPingAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TailClientUpdateOne) SetUpdatedAt(v time.Time) *TailClientUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddDiagnosticRunIDs adds the "diagnostic_runs" edge to the DiagnosticRun entity by IDs.
func (_u *TailClientUpdateOne) AddDiagnosticRunIDs(ids ...string) *TailClientUpdateOne {
	_u.mutation.AddDiagnosticRunIDs(ids...)
	return _u
}

// AddDiagnosticRuns adds the "diagnostic_runs" edges to the DiagnosticRun entity.
func (_u *TailClientUpdateOne) AddDiagnosticRuns(v ...*DiagnosticRun) *TailClientUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDiagnosticRunIDs(ids...)
}

// AddRouteIDs adds the "routes" edge to the PublishedRoute entity by IDs.
func (_u *TailClientUpdateOne) AddRouteIDs(ids ...string) *TailClientUpdateOne {
	_u.mutation.AddRouteIDs(ids...)
	return _u
}

// AddRoutes adds the "routes" edges to the PublishedRoute entity.
func (_u *TailClientUpdateOne) AddRoutes(v ...*PublishedRoute) *TailClientUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRouteIDs(ids...)
}

// AddTransferJobIDs adds the "transfer_jobs" edge to the TransferJob entity by IDs.
func (_u *TailClientUpdateOne) AddTransferJobIDs(ids ...string) *TailClientUpdateOne {
	_u.mutation.AddTransferJobIDs(ids...)
	return _u
}

// AddTransferJobs adds the "transfer_jobs" edges to the TransferJob entity.
func (_u *TailClientUpdateOne) AddTransferJobs(v ...*TransferJob) *TailClientUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransferJobIDs(ids...)
}

// Mutation returns the TailClientMutation object of the builder.
func (_u *TailClientUpdateOne) Mutation() *TailClientMutation {
	return _u.mutation
}

// ClearDiagnosticRuns clears all "diagnostic_runs" edges to the DiagnosticRun entity.
func (_u *TailClientUpdateOne) ClearDiagnosticRuns() *TailClientUpdateOne {
	_u.mutation.ClearDiagnosticRuns()
	return _u
}

// RemoveDiagnosticRunIDs removes the "diagnostic_runs" edge to DiagnosticRun entities by IDs.
func (_u *TailClientUpdateOne) RemoveDiagnosticRunIDs(ids ...string) *TailClientUpdateOne {
	_u.mutation.RemoveDiagnosticRunIDs(ids...)
	return _u
}

// RemoveDiagnosticRuns removes "diagnostic_runs" edges to DiagnosticRun entities.
func (_u *TailClientUpdateOne) RemoveDiagnosticRuns(v ...*DiagnosticRun) *TailClientUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDiagnosticRunIDs(ids...)
}

// ClearRoutes clears all "routes" edges to the PublishedRoute entity.
func (_u *TailClientUpdateOne) ClearRoutes() *TailClientUpdateOne {
	_u.mutation.ClearRoutes()
	return _u
}

// RemoveRouteIDs removes the "routes" edge to PublishedRoute entities by IDs.
func (_u *TailClientUpdateOne) RemoveRouteIDs(ids ...string) *TailClientUpdateOne {
	_u.mutation.RemoveRouteIDs(ids...)
	return _u
}

// RemoveRoutes removes "routes" edges to PublishedRoute entities.
func (_u *TailClientUpdateOne) RemoveRoutes(v ...*PublishedRoute) *TailClientUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRouteIDs(ids...)
}

// ClearTransferJobs clears all "transfer_jobs" edges to the TransferJob entity.
func (_u *TailClientUpdateOne) ClearTransferJobs() *TailClientUpdateOne {
	_u.mutation.ClearTransferJobs()
	return _u
}

// RemoveTransferJobIDs removes the "transfer_jobs" edge to TransferJob entities by IDs.
func (_u *TailClientUpdateOne) RemoveTransferJobIDs(ids ...string) *TailClientUpdateOne {
	_u.mutation.RemoveTransferJobIDs(ids...)
	return _u
}

// RemoveTransferJobs removes "transfer_jobs" edges to TransferJob entities.
func (_u *TailClientUpdateOne) RemoveTransferJobs(v ...*TransferJob) *TailClientUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransferJobIDs(ids...)
}

// Where appends a list predicates to the TailClientUpdate builder.
func (_u *TailClientUpdateOne) Where(ps ...predicate.TailClient) *TailClientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TailClientUpdateOne) Select(field string, fields ...string) *TailClientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TailClient entity.
func (_u *TailClientUpdateOne) Save(ctx context.Context) (*TailClient, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TailClientUpdateOne) SaveX(ctx context.Context) *TailClient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TailClientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TailClientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TailClientUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tailclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TailClientUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tailclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TailClient.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServerTokenCipher(); ok {
		if err := tailclient.ServerTokenCipherValidator(v); err != nil {
			return &ValidationError{Name: "server_token_cipher", err: fmt.Errorf(`ent: validator failed for field "TailClient.server_token_cipher": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHint(); ok {
		if err := tailclient.TokenHintValidator(v); err != nil {
			return &ValidationError{Name: "token_hint", err: fmt.Errorf(`ent: validator failed for field "TailClient.token_hint": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TailClient.owner"`)
	}
	return nil
}

func (_u *TailClientUpdateOne) sqlSave(ctx context.Context) (_node *TailClient, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tailclient.Table, tailclient.Columns, sqlgraph.NewFieldSpec(tailclient.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TailClient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tailclient.FieldID)
		for _, f := range fields {
			if !tailclient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tailclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tailclient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServerTokenCipher(); ok {
		_spec.SetField(tailclient.FieldServerTokenCipher, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.TokenHint(); ok {
		_spec.SetField(tailclient.FieldTokenHint, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyCipher(); ok {
		_spec.SetField(tailclient.FieldKeyCipher, field.TypeBytes, value)
	}
	if _u.mutation.KeyCipherCleared() {
		_spec.ClearField(tailclient.FieldKeyCipher, field.TypeBytes)
	}
	if value, ok := _u.mutation.DerpMapURL(); ok {
		_spec.SetField(tailclient.FieldDerpMapURL, field.TypeString, value)
	}
	if _u.mutation.DerpMapURLCleared() {
		_spec.ClearField(tailclient.FieldDerpMapURL, field.TypeString)
	}
	if value, ok := _u.mutation.LastPingMs(); ok {
		_spec.SetField(tailclient.FieldLastPingMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastPingMs(); ok {
		_spec.AddField(tailclient.FieldLastPingMs, field.TypeInt64, value)
	}
	if _u.mutation.LastPingMsCleared() {
		_spec.ClearField(tailclient.FieldLastPingMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastPath(); ok {
		_spec.SetField(tailclient.FieldLastPath, field.TypeString, value)
	}
	if _u.mutation.LastPathCleared() {
		_spec.ClearField(tailclient.FieldLastPath, field.TypeString)
	}
	if value, ok := _u.mutation.LastPingAt(); ok {
		_spec.SetField(tailclient.FieldLastPingAt, field.TypeTime, value)
	}
	if _u.mutation.LastPingAtCleared() {
		_spec.ClearField(tailclient.FieldLastPingAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tailclient.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.DiagnosticRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.DiagnosticRunsTable,
			Columns: []string{tailclient.DiagnosticRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagnosticrun.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDiagnosticRunsIDs(); len(nodes) > 0 && !_u.mutation.DiagnosticRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.DiagnosticRunsTable,
			Columns: []string{tailclient.DiagnosticRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagnosticrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DiagnosticRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.DiagnosticRunsTable,
			Columns: []string{tailclient.DiagnosticRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagnosticrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.RoutesTable,
			Columns: []string{tailclient.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publishedroute.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoutesIDs(); len(nodes) > 0 && !_u.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.RoutesTable,
			Columns: []string{tailclient.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publishedroute.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.RoutesTable,
			Columns: []string{tailclient.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publishedroute.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransferJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.TransferJobsTable,
			Columns: []string{tailclient.TransferJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferjob.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransferJobsIDs(); len(nodes) > 0 && !_u.mutation.TransferJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.TransferJobsTable,
			Columns: []string{tailclient.TransferJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransferJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tailclient.TransferJobsTable,
			Columns: []string{tailclient.TransferJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TailClient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tailclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
