// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/tailcat-webui/ent/sharefile"
	"github.com/ca-x/tailcat-webui/ent/tailserver"
	"github.com/ca-x/tailcat-webui/ent/transfershare"
	"github.com/ca-x/tailcat-webui/ent/user"
)

// TransferShareCreate is the builder for creating a TransferShare entity.
type TransferShareCreate struct {
	config
	mutation *TransferShareMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *TransferShareCreate) SetUserID(v string) *TransferShareCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetServerID sets the "server_id" field.
func (_c *TransferShareCreate) SetServerID(v string) *TransferShareCreate {
	_c.mutation.SetServerID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TransferShareCreate) SetStatus(v transfershare.Status) *TransferShareCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TransferShareCreate) SetNillableStatus(v *transfershare.Status) *TransferShareCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCapabilityHash sets the "capability_hash" field.
func (_c *TransferShareCreate) SetCapabilityHash(v []byte) *TransferShareCreate {
	_c.mutation.SetCapabilityHash(v)
	return _c
}

// SetTotalBytes sets the "total_bytes" field.
func (_c *TransferShareCreate) SetTotalBytes(v int64) *TransferShareCreate {
	_c.mutation.SetTotalBytes(v)
	return _c
}

// SetNillableTotalBytes sets the "total_bytes" field if the given value is not nil.
func (_c *TransferShareCreate) SetNillableTotalBytes(v *int64) *TransferShareCreate {
	if v != nil {
		_c.SetTotalBytes(*v)
	}
	return _c
}

// SetFileCount sets the "file_count" field.
func (_c *TransferShareCreate) SetFileCount(v int) *TransferShareCreate {
	_c.mutation.SetFileCount(v)
	return _c
}

// SetNillableFileCount sets the "file_count" field if the given value is not nil.
func (_c *TransferShareCreate) SetNillableFileCount(v *int) *TransferShareCreate {
	if v != nil {
		_c.SetFileCount(*v)
	}
	return _c
}

// SetReadyAt sets the "ready_at" field.
func (_c *TransferShareCreate) SetReadyAt(v time.Time) *TransferShareCreate {
	_c.mutation.SetReadyAt(v)
	return _c
}

// SetNillableReadyAt sets the "ready_at" field if the given value is not nil.
func (_c *TransferShareCreate) SetNillableReadyAt(v *time.Time) *TransferShareCreate {
	if v != nil {
		_c.SetReadyAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *TransferShareCreate) SetFinishedAt(v time.Time) *TransferShareCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *TransferShareCreate) SetNillableFinishedAt(v *time.Time) *TransferShareCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *TransferShareCreate) SetExpiresAt(v time.Time) *TransferShareCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *TransferShareCreate) SetErrorCode(v transfershare.ErrorCode) *TransferShareCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *TransferShareCreate) SetNillableErrorCode(v *transfershare.ErrorCode) *TransferShareCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TransferShareCreate) SetCreatedAt(v time.Time) *TransferShareCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TransferShareCreate) SetNillableCreatedAt(v *time.Time) *TransferShareCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TransferShareCreate) SetUpdatedAt(v time.Time) *TransferShareCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TransferShareCreate) SetNillableUpdatedAt(v *time.Time) *TransferShareCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TransferShareCreate) SetID(v string) *TransferShareCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TransferShareCreate) SetNillableID(v *string) *TransferShareCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *TransferShareCreate) SetOwnerID(id string) *TransferShareCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *TransferShareCreate) SetOwner(v *User) *TransferShareCreate {
	return _c.SetOwnerID(v.ID)
}

// SetServer sets the "server" edge to the TailServer entity.
func (_c *TransferShareCreate) SetServer(v *TailServer) *TransferShareCreate {
	return _c.SetServerID(v.ID)
}

// AddFileIDs adds the "files" edge to the ShareFile entity by IDs.
func (_c *TransferShareCreate) AddFileIDs(ids ...string) *TransferShareCreate {
	_c.mutation.AddFileIDs(ids...)
	return _c
}

// AddFiles adds the "files" edges to the ShareFile entity.
func (_c *TransferShareCreate) AddFiles(v ...*ShareFile) *TransferShareCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFileIDs(ids...)
}

// Mutation returns the TransferShareMutation object of the builder.
func (_c *TransferShareCreate) Mutation() *TransferShareMutation {
	return _c.mutation
}

// Save creates the TransferShare in the database.
func (_c *TransferShareCreate) Save(ctx context.Context) (*TransferShare, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TransferShareCreate) SaveX(ctx context.Context) *TransferShare {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransferShareCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransferShareCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TransferShareCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := transfershare.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalBytes(); !ok {
		v := transfershare.DefaultTotalBytes
		_c.mutation.SetTotalBytes(v)
	}
	if _, ok := _c.mutation.FileCount(); !ok {
		v := transfershare.DefaultFileCount
		_c.mutation.SetFileCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := transfershare.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := transfershare.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := transfershare.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TransferShareCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TransferShare.user_id"`)}
	}
	if _, ok := _c.mutation.ServerID(); !ok {
		return &ValidationError{Name: "server_id", err: errors.New(`ent: missing required field "TransferShare.server_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TransferShare.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := transfershare.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TransferShare.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CapabilityHash(); !ok {
		return &ValidationError{Name: "capability_hash", err: errors.New(`ent: missing required field "TransferShare.capability_hash"`)}
	}
	if v, ok := _c.mutation.CapabilityHash(); ok {
		if err := transfershare.CapabilityHashValidator(v); err != nil {
			return &ValidationError{Name: "capability_hash", err: fmt.Errorf(`ent: validator failed for field "TransferShare.capability_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalBytes(); !ok {
		return &ValidationError{Name: "total_bytes", err: errors.New(`ent: missing required field "TransferShare.total_bytes"`)}
	}
	if v, ok := _c.mutation.TotalBytes(); ok {
		if err := transfershare.TotalBytesValidator(v); err != nil {
			return &ValidationError{Name: "total_bytes", err: fmt.Errorf(`ent: validator failed for field "TransferShare.total_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileCount(); !ok {
		return &ValidationError{Name: "file_count", err: errors.New(`ent: missing required field "TransferShare.file_count"`)}
	}
	if v, ok := _c.mutation.FileCount(); ok {
		if err := transfershare.FileCountValidator(v); err != nil {
			return &ValidationError{Name: "file_count", err: fmt.Errorf(`ent: validator failed for field "TransferShare.file_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "TransferShare.expires_at"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := transfershare.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "TransferShare.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TransferShare.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TransferShare.updated_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "TransferShare.owner"`)}
	}
	if len(_c.mutation.ServerIDs()) == 0 {
		return &ValidationError{Name: "server", err: errors.New(`ent: missing required edge "TransferShare.server"`)}
	}
	return nil
}

func (_c *TransferShareCreate) sqlSave(ctx context.Context) (*TransferShare, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TransferShare.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TransferShareCreate) createSpec() (*TransferShare, *sqlgraph.CreateSpec) {
	var (
		_node = &TransferShare{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(transfershare.Table, sqlgraph.NewFieldSpec(transfershare.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(transfershare.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CapabilityHash(); ok {
		_spec.SetField(transfershare.FieldCapabilityHash, field.TypeBytes, value)
		_node.CapabilityHash = value
	}
	if value, ok := _c.mutation.TotalBytes(); ok {
		_spec.SetField(transfershare.FieldTotalBytes, field.TypeInt64, value)
		_node.TotalBytes = value
	}
	if value, ok := _c.mutation.FileCount(); ok {
		_spec.SetField(transfershare.FieldFileCount, field.TypeInt, value)
		_node.FileCount = value
	}
	if value, ok := _c.mutation.ReadyAt(); ok {
		_spec.SetField(transfershare.FieldReadyAt, field.TypeTime, value)
		_node.ReadyAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(transfershare.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(transfershare.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(transfershare.FieldErrorCode, field.TypeEnum, value)
		_node.ErrorCode = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(transfershare.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(transfershare.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transfershare.OwnerTable,
			Columns: []string{transfershare.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transfershare.ServerTable,
			Columns: []string{transfershare.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tailserver.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ServerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transfershare.FilesTable,
			Columns: []string{transfershare.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharefile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TransferShareCreateBulk is the builder for creating many TransferShare entities in bulk.
type TransferShareCreateBulk struct {
	config
	err      error
	builders []*TransferShareCreate
}

// Save creates the TransferShare entities in the database.
func (_c *TransferShareCreateBulk) Save(ctx context.Context) ([]*TransferShare, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TransferShare, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransferShareMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TransferShareCreateBulk) SaveX(ctx context.Context) []*TransferShare {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransferShareCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransferShareCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
