// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/tailcat-webui/ent/tailclient"
	"github.com/ca-x/tailcat-webui/ent/transferjob"
	"github.com/ca-x/tailcat-webui/ent/user"
)

// TransferJob is the model entity for the TransferJob schema.
type TransferJob struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// RemoteShareID holds the value of the "remote_share_id" field.
	RemoteShareID string `json:"remote_share_id,omitempty"`
	// RemoteCapabilityCipher holds the value of the "remote_capability_cipher" field.
	RemoteCapabilityCipher []byte `json:"-"`
	// Status holds the value of the "status" field.
	Status transferjob.Status `json:"status,omitempty"`
	// TotalBytes holds the value of the "total_bytes" field.
	TotalBytes int64 `json:"total_bytes,omitempty"`
	// ReceivedBytes holds the value of the "received_bytes" field.
	ReceivedBytes int64 `json:"received_bytes,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode transferjob.ErrorCode `json:"error_code,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TransferJobQuery when eager-loading is set.
	Edges        TransferJobEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TransferJobEdges holds the relations/edges for other nodes in the graph.
type TransferJobEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Client holds the value of the client edge.
	Client *TailClient `json:"client,omitempty"`
	// Items holds the value of the items edge.
	Items []*TransferItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransferJobEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// ClientOrErr returns the Client value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransferJobEdges) ClientOrErr() (*TailClient, error) {
	if e.Client != nil {
		return e.Client, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: tailclient.Label}
	}
	return nil, &NotLoadedError{edge: "client"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e TransferJobEdges) ItemsOrErr() ([]*TransferItem, error) {
	if e.loadedTypes[2] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TransferJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case transferjob.FieldRemoteCapabilityCipher:
			values[i] = new([]byte)
		case transferjob.FieldTotalBytes, transferjob.FieldReceivedBytes:
			values[i] = new(sql.NullInt64)
		case transferjob.FieldID, transferjob.FieldUserID, transferjob.FieldClientID, transferjob.FieldRemoteShareID, transferjob.FieldStatus, transferjob.FieldErrorCode:
			values[i] = new(sql.NullString)
		case transferjob.FieldStartedAt, transferjob.FieldFinishedAt, transferjob.FieldExpiresAt, transferjob.FieldCreatedAt, transferjob.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TransferJob fields.
func (_m *TransferJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transferjob.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case transferjob.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case transferjob.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case transferjob.FieldRemoteShareID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_share_id", values[i])
			} else if value.Valid {
				_m.RemoteShareID = value.String
			}
		case transferjob.FieldRemoteCapabilityCipher:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field remote_capability_cipher", values[i])
			} else if value != nil {
				_m.RemoteCapabilityCipher = *value
			}
		case transferjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = transferjob.Status(value.String)
			}
		case transferjob.FieldTotalBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_bytes", values[i])
			} else if value.Valid {
				_m.TotalBytes = value.Int64
			}
		case transferjob.FieldReceivedBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field received_bytes", values[i])
			} else if value.Valid {
				_m.ReceivedBytes = value.Int64
			}
		case transferjob.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case transferjob.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case transferjob.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case transferjob.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = transferjob.ErrorCode(value.String)
			}
		case transferjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case transferjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TransferJob.
// This includes values selected through modifiers, order, etc.
func (_m *TransferJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the TransferJob entity.
func (_m *TransferJob) QueryOwner() *UserQuery {
	return NewTransferJobClient(_m.config).QueryOwner(_m)
}

// QueryClient queries the "client" edge of the TransferJob entity.
func (_m *TransferJob) QueryClient() *TailClientQuery {
	return NewTransferJobClient(_m.config).QueryClient(_m)
}

// QueryItems queries the "items" edge of the TransferJob entity.
func (_m *TransferJob) QueryItems() *TransferItemQuery {
	return NewTransferJobClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this TransferJob.
// Note that you need to call TransferJob.Unwrap() before calling this method if this TransferJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TransferJob) Update() *TransferJobUpdateOne {
	return NewTransferJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TransferJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TransferJob) Unwrap() *TransferJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TransferJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TransferJob) String() string {
	var builder strings.Builder
	builder.WriteString("TransferJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("remote_share_id=")
	builder.WriteString(_m.RemoteShareID)
	builder.WriteString(", ")
	builder.WriteString("remote_capability_cipher=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("total_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalBytes))
	builder.WriteString(", ")
	builder.WriteString("received_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReceivedBytes))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("error_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorCode))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TransferJobs is a parsable slice of TransferJob.
type TransferJobs []*TransferJob
