// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/tailcat-webui/ent/predicate"
	"github.com/ca-x/tailcat-webui/ent/sharefile"
	"github.com/ca-x/tailcat-webui/ent/tailserver"
	"github.com/ca-x/tailcat-webui/ent/transfershare"
	"github.com/ca-x/tailcat-webui/ent/user"
)

// TransferShareQuery is the builder for querying TransferShare entities.
type TransferShareQuery struct {
	config
	ctx        *QueryContext
	order      []transfershare.OrderOption
	inters     []Interceptor
	predicates []predicate.TransferShare
	withOwner  *UserQuery
	withServer *TailServerQuery
	withFiles  *ShareFileQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TransferShareQuery builder.
func (_q *TransferShareQuery) Where(ps ...predicate.TransferShare) *TransferShareQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TransferShareQuery) Limit(limit int) *TransferShareQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TransferShareQuery) Offset(offset int) *TransferShareQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TransferShareQuery) Unique(unique bool) *TransferShareQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TransferShareQuery) Order(o ...transfershare.OrderOption) *TransferShareQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOwner chains the current query on the "owner" edge.
func (_q *TransferShareQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transfershare.Table, transfershare.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, transfershare.OwnerTable, transfershare.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryServer chains the current query on the "server" edge.
func (_q *TransferShareQuery) QueryServer() *TailServerQuery {
	query := (&TailServerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transfershare.Table, transfershare.FieldID, selector),
			sqlgraph.To(tailserver.Table, tailserver.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, transfershare.ServerTable, transfershare.ServerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFiles chains the current query on the "files" edge.
func (_q *TransferShareQuery) QueryFiles() *ShareFileQuery {
	query := (&ShareFileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transfershare.Table, transfershare.FieldID, selector),
			sqlgraph.To(sharefile.Table, sharefile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, transfershare.FilesTable, transfershare.FilesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TransferShare entity from the query.
// Returns a *NotFoundError when no TransferShare was found.
func (_q *TransferShareQuery) First(ctx context.Context) (*TransferShare, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{transfershare.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TransferShareQuery) FirstX(ctx context.Context) *TransferShare {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TransferShare ID from the query.
// Returns a *NotFoundError when no TransferShare ID was found.
func (_q *TransferShareQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{transfershare.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TransferShareQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TransferShare entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TransferShare entity is found.
// Returns a *NotFoundError when no TransferShare entities are found.
func (_q *TransferShareQuery) Only(ctx context.Context) (*TransferShare, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{transfershare.Label}
	default:
		return nil, &NotSingularError{transfershare.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TransferShareQuery) OnlyX(ctx context.Context) *TransferShare {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TransferShare ID in the query.
// Returns a *NotSingularError when more than one TransferShare ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TransferShareQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{transfershare.Label}
	default:
		err = &NotSingularError{transfershare.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TransferShareQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TransferShares.
func (_q *TransferShareQuery) All(ctx context.Context) ([]*TransferShare, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TransferShare, *TransferShareQuery]()
	return withInterceptors[[]*TransferShare](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TransferShareQuery) AllX(ctx context.Context) []*TransferShare {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TransferShare IDs.
func (_q *TransferShareQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(transfershare.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TransferShareQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TransferShareQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TransferShareQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TransferShareQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TransferShareQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TransferShareQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TransferShareQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TransferShareQuery) Clone() *TransferShareQuery {
	if _q == nil {
		return nil
	}
	return &TransferShareQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]transfershare.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.TransferShare{}, _q.predicates...),
		withOwner:  _q.withOwner.Clone(),
		withServer: _q.withServer.Clone(),
		withFiles:  _q.withFiles.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TransferShareQuery) WithOwner(opts ...func(*UserQuery)) *TransferShareQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOwner = query
	return _q
}

// WithServer tells the query-builder to eager-load the nodes that are connected to
// the "server" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TransferShareQuery) WithServer(opts ...func(*TailServerQuery)) *TransferShareQuery {
	query := (&TailServerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withServer = query
	return _q
}

// WithFiles tells the query-builder to eager-load the nodes that are connected to
// the "files" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TransferShareQuery) WithFiles(opts ...func(*ShareFileQuery)) *TransferShareQuery {
	query := (&ShareFileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFiles = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TransferShare.Query().
//		GroupBy(transfershare.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *TransferShareQuery) GroupBy(field string, fields ...string) *TransferShareGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TransferShareGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = transfershare.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.TransferShare.Query().
//		Select(transfershare.FieldUserID).
//		Scan(ctx, &v)
func (_q *TransferShareQuery) Select(fields ...string) *TransferShareSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TransferShareSelect{TransferShareQuery: _q}
	sbuild.label = transfershare.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TransferShareSelect configured with the given aggregations.
func (_q *TransferShareQuery) Aggregate(fns ...AggregateFunc) *TransferShareSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TransferShareQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !transfershare.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TransferShareQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TransferShare, error) {
	var (
		nodes       = []*TransferShare{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withOwner != nil,
			_q.withServer != nil,
			_q.withFiles != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TransferShare).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TransferShare{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOwner; query != nil {
		if err := _q.loadOwner(ctx, query, nodes, nil,
			func(n *TransferShare, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withServer; query != nil {
		if err := _q.loadServer(ctx, query, nodes, nil,
			func(n *TransferShare, e *TailServer) { n.Edges.Server = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFiles; query != nil {
		if err := _q.loadFiles(ctx, query, nodes,
			func(n *TransferShare) { n.Edges.Files = []*ShareFile{} },
			func(n *TransferShare, e *ShareFile) { n.Edges.Files = append(n.Edges.Files, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TransferShareQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*TransferShare, init func(*TransferShare), assign func(*TransferShare, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*TransferShare)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *TransferShareQuery) loadServer(ctx context.Context, query *TailServerQuery, nodes []*TransferShare, init func(*TransferShare), assign func(*TransferShare, *TailServer)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*TransferShare)
	for i := range nodes {
		fk := nodes[i].ServerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tailserver.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "server_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *TransferShareQuery) loadFiles(ctx context.Context, query *ShareFileQuery, nodes []*TransferShare, init func(*TransferShare), assign func(*TransferShare, *ShareFile)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*TransferShare)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(sharefile.FieldShareID)
	}
	query.Where(predicate.ShareFile(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(transfershare.FilesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ShareID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "share_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *TransferShareQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TransferShareQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(transfershare.Table, transfershare.Columns, sqlgraph.NewFieldSpec(transfershare.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transfershare.FieldID)
		for i := range fields {
			if fields[i] != transfershare.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withOwner != nil {
			_spec.Node.AddColumnOnce(transfershare.FieldUserID)
		}
		if _q.withServer != nil {
			_spec.Node.AddColumnOnce(transfershare.FieldServerID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TransferShareQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(transfershare.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = transfershare.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TransferShareGroupBy is the group-by builder for TransferShare entities.
type TransferShareGroupBy struct {
	selector
	build *TransferShareQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TransferShareGroupBy) Aggregate(fns ...AggregateFunc) *TransferShareGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TransferShareGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransferShareQuery, *TransferShareGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TransferShareGroupBy) sqlScan(ctx context.Context, root *TransferShareQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TransferShareSelect is the builder for selecting fields of TransferShare entities.
type TransferShareSelect struct {
	*TransferShareQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TransferShareSelect) Aggregate(fns ...AggregateFunc) *TransferShareSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TransferShareSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransferShareQuery, *TransferShareSelect](ctx, _s.TransferShareQuery, _s, _s.inters, v)
}

func (_s *TransferShareSelect) sqlScan(ctx context.Context, root *TransferShareQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
