// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/tailcat-webui/ent/predicate"
	"github.com/ca-x/tailcat-webui/ent/transferitem"
)

// TransferItemUpdate is the builder for updating TransferItem entities.
type TransferItemUpdate struct {
	config
	hooks    []Hook
	mutation *TransferItemMutation
}

// Where appends a list predicates to the TransferItemUpdate builder.
func (_u *TransferItemUpdate) Where(ps ...predicate.TransferItem) *TransferItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCompletedBlocks sets the "completed_blocks" field.
func (_u *TransferItemUpdate) SetCompletedBlocks(v []int) *TransferItemUpdate {
	_u.mutation.SetCompletedBlocks(v)
	return _u
}

// AppendCompletedBlocks appends value to the "completed_blocks" field.
func (_u *TransferItemUpdate) AppendCompletedBlocks(v []int) *TransferItemUpdate {
	_u.mutation.AppendCompletedBlocks(v)
	return _u
}

// SetReceivedBytes sets the "received_bytes" field.
func (_u *TransferItemUpdate) SetReceivedBytes(v int64) *TransferItemUpdate {
	_u.mutation.ResetReceivedBytes()
	_u.mutation.SetReceivedBytes(v)
	return _u
}

// SetNillableReceivedBytes sets the "received_bytes" field if the given value is not nil.
func (_u *TransferItemUpdate) SetNillableReceivedBytes(v *int64) *TransferItemUpdate {
	if v != nil {
		_u.SetReceivedBytes(*v)
	}
	return _u
}

// AddReceivedBytes adds value to the "received_bytes" field.
func (_u *TransferItemUpdate) AddReceivedBytes(v int64) *TransferItemUpdate {
	_u.mutation.AddReceivedBytes(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TransferItemUpdate) SetStatus(v transferitem.Status) *TransferItemUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TransferItemUpdate) SetNillableStatus(v *transferitem.Status) *TransferItemUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *TransferItemUpdate) SetStartedAt(v time.Time) *TransferItemUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *TransferItemUpdate) SetNillableStartedAt(v *time.Time) *TransferItemUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *TransferItemUpdate) ClearStartedAt() *TransferItemUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *TransferItemUpdate) SetFinishedAt(v time.Time) *TransferItemUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *TransferItemUpdate) SetNillableFinishedAt(v *time.Time) *TransferItemUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *TransferItemUpdate) ClearFinishedAt() *TransferItemUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *TransferItemUpdate) SetErrorCode(v transferitem.ErrorCode) *TransferItemUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *TransferItemUpdate) SetNillableErrorCode(v *transferitem.ErrorCode) *TransferItemUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *TransferItemUpdate) ClearErrorCode() *TransferItemUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TransferItemUpdate) SetUpdatedAt(v time.Time) *TransferItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TransferItemMutation object of the builder.
func (_u *TransferItemUpdate) Mutation() *TransferItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TransferItemUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransferItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TransferItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransferItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TransferItemUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if transferitem.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized transferitem.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := transferitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransferItemUpdate) check() error {
	if v, ok := _u.mutation.ReceivedBytes(); ok {
		if err := transferitem.ReceivedBytesValidator(v); err != nil {
			return &ValidationError{Name: "received_bytes", err: fmt.Errorf(`ent: validator failed for field "TransferItem.received_bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := transferitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TransferItem.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := transferitem.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "TransferItem.error_code": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransferItem.owner"`)
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransferItem.job"`)
	}
	return nil
}

func (_u *TransferItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transferitem.Table, transferitem.Columns, sqlgraph.NewFieldSpec(transferitem.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompletedBlocks(); ok {
		_spec.SetField(transferitem.FieldCompletedBlocks, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCompletedBlocks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, transferitem.FieldCompletedBlocks, value)
		})
	}
	if value, ok := _u.mutation.ReceivedBytes(); ok {
		_spec.SetField(transferitem.FieldReceivedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReceivedBytes(); ok {
		_spec.AddField(transferitem.FieldReceivedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(transferitem.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(transferitem.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(transferitem.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(transferitem.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(transferitem.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(transferitem.FieldErrorCode, field.TypeEnum, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(transferitem.FieldErrorCode, field.TypeEnum)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transferitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transferitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TransferItemUpdateOne is the builder for updating a single TransferItem entity.
type TransferItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransferItemMutation
}

// SetCompletedBlocks sets the "completed_blocks" field.
func (_u *TransferItemUpdateOne) SetCompletedBlocks(v []int) *TransferItemUpdateOne {
	_u.mutation.SetCompletedBlocks(v)
	return _u
}

// AppendCompletedBlocks appends value to the "completed_blocks" field.
func (_u *TransferItemUpdateOne) AppendCompletedBlocks(v []int) *TransferItemUpdateOne {
	_u.mutation.AppendCompletedBlocks(v)
	return _u
}

// SetReceivedBytes sets the "received_bytes" field.
func (_u *TransferItemUpdateOne) SetReceivedBytes(v int64) *TransferItemUpdateOne {
	_u.mutation.ResetReceivedBytes()
	_u.mutation.SetReceivedBytes(v)
	return _u
}

// SetNillableReceivedBytes sets the "received_bytes" field if the given value is not nil.
func (_u *TransferItemUpdateOne) SetNillableReceivedBytes(v *int64) *TransferItemUpdateOne {
	if v != nil {
		_u.SetReceivedBytes(*v)
	}
	return _u
}

// AddReceivedBytes adds value to the "received_bytes" field.
func (_u *TransferItemUpdateOne) AddReceivedBytes(v int64) *TransferItemUpdateOne {
	_u.mutation.AddReceivedBytes(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TransferItemUpdateOne) SetStatus(v transferitem.Status) *TransferItemUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TransferItemUpdateOne) SetNillableStatus(v *transferitem.Status) *TransferItemUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *TransferItemUpdateOne) SetStartedAt(v time.Time) *TransferItemUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *TransferItemUpdateOne) SetNillableStartedAt(v *time.Time) *TransferItemUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *TransferItemUpdateOne) ClearStartedAt() *TransferItemUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *TransferItemUpdateOne) SetFinishedAt(v time.Time) *TransferItemUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *TransferItemUpdateOne) SetNillableFinishedAt(v *time.Time) *TransferItemUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *TransferItemUpdateOne) ClearFinishedAt() *TransferItemUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *TransferItemUpdateOne) SetErrorCode(v transferitem.ErrorCode) *TransferItemUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *TransferItemUpdateOne) SetNillableErrorCode(v *transferitem.ErrorCode) *TransferItemUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *TransferItemUpdateOne) ClearErrorCode() *TransferItemUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TransferItemUpdateOne) SetUpdatedAt(v time.Time) *TransferItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TransferItemMutation object of the builder.
func (_u *TransferItemUpdateOne) Mutation() *TransferItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the TransferItemUpdate builder.
func (_u *TransferItemUpdateOne) Where(ps ...predicate.TransferItem) *TransferItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TransferItemUpdateOne) Select(field string, fields ...string) *TransferItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TransferItem entity.
func (_u *TransferItemUpdateOne) Save(ctx context.Context) (*TransferItem, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransferItemUpdateOne) SaveX(ctx context.Context) *TransferItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TransferItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransferItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TransferItemUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if transferitem.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized transferitem.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := transferitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransferItemUpdateOne) check() error {
	if v, ok := _u.mutation.ReceivedBytes(); ok {
		if err := transferitem.ReceivedBytesValidator(v); err != nil {
			return &ValidationError{Name: "received_bytes", err: fmt.Errorf(`ent: validator failed for field "TransferItem.received_bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := transferitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TransferItem.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := transferitem.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "TransferItem.error_code": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransferItem.owner"`)
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransferItem.job"`)
	}
	return nil
}

func (_u *TransferItemUpdateOne) sqlSave(ctx context.Context) (_node *TransferItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transferitem.Table, transferitem.Columns, sqlgraph.NewFieldSpec(transferitem.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TransferItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transferitem.FieldID)
		for _, f := range fields {
			if !transferitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transferitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompletedBlocks(); ok {
		_spec.SetField(transferitem.FieldCompletedBlocks, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCompletedBlocks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, transferitem.FieldCompletedBlocks, value)
		})
	}
	if value, ok := _u.mutation.ReceivedBytes(); ok {
		_spec.SetField(transferitem.FieldReceivedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReceivedBytes(); ok {
		_spec.AddField(transferitem.FieldReceivedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(transferitem.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(transferitem.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(transferitem.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(transferitem.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(transferitem.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(transferitem.FieldErrorCode, field.TypeEnum, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(transferitem.FieldErrorCode, field.TypeEnum)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transferitem.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TransferItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transferitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
