// Code generated by ent, DO NOT EDIT.

package publishedroute

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the publishedroute type in the database.
	Label = "published_route"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldRemotePort holds the string denoting the remote_port field in the database.
	FieldRemotePort = "remote_port"
	// FieldBasePath holds the string denoting the base_path field in the database.
	FieldBasePath = "base_path"
	// FieldAccess holds the string denoting the access field in the database.
	FieldAccess = "access"
	// FieldAllowedMethods holds the string denoting the allowed_methods field in the database.
	FieldAllowedMethods = "allowed_methods"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeClient holds the string denoting the client edge name in mutations.
	EdgeClient = "client"
	// Table holds the table name of the publishedroute in the database.
	Table = "published_routes"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "published_routes"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_id"
	// ClientTable is the table that holds the client relation/edge.
	ClientTable = "published_routes"
	// ClientInverseTable is the table name for the TailClient entity.
	// It exists in this package in order to avoid circular dependency with the "tailclient" package.
	ClientInverseTable = "tail_clients"
	// ClientColumn is the table column denoting the client relation/edge.
	ClientColumn = "client_id"
)

// Columns holds all SQL columns for publishedroute fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldClientID,
	FieldName,
	FieldSlug,
	FieldRemotePort,
	FieldBasePath,
	FieldAccess,
	FieldAllowedMethods,
	FieldEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// DefaultBasePath holds the default value on creation for the "base_path" field.
	DefaultBasePath string
	// DefaultAllowedMethods holds the default value on creation for the "allowed_methods" field.
	DefaultAllowedMethods []string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// Access defines the type for the "access" enum field.
type Access string

// AccessPrivate is the default value of the Access enum.
const DefaultAccess = AccessPrivate

// Access values.
const (
	AccessPrivate Access = "private"
	AccessPublic  Access = "public"
)

func (a Access) String() string {
	return string(a)
}

// AccessValidator is a validator for the "access" field enum values. It is called by the builders before save.
func AccessValidator(a Access) error {
	switch a {
	case AccessPrivate, AccessPublic:
		return nil
	default:
		return fmt.Errorf("publishedroute: invalid enum value for access field: %q", a)
	}
}

// OrderOption defines the ordering options for the PublishedRoute queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByRemotePort orders the results by the remote_port field.
func ByRemotePort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemotePort, opts...).ToFunc()
}

// ByBasePath orders the results by the base_path field.
func ByBasePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBasePath, opts...).ToFunc()
}

// ByAccess orders the results by the access field.
func ByAccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccess, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByClientField orders the results by client field.
func ByClientField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClientStep(), sql.OrderByField(field, opts...))
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
func newClientStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClientInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ClientTable, ClientColumn),
	)
}
