// Code generated by ent, DO NOT EDIT.

package tailserver

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ca-x/tailcat-webui/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TailServer {
	return predicate.TailServer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TailServer {
	return predicate.TailServer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TailServer {
	return predicate.TailServer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TailServer {
	return predicate.TailServer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TailServer {
	return predicate.TailServer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TailServer {
	return predicate.TailServer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TailServer {
	return predicate.TailServer(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TailServer {
	return predicate.TailServer(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldName, v))
}

// KeyCipher applies equality check predicate on the "key_cipher" field. It's identical to KeyCipherEQ.
func KeyCipher(v []byte) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldKeyCipher, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldRegion, v))
}

// DerpMapURL applies equality check predicate on the "derp_map_url" field. It's identical to DerpMapURLEQ.
func DerpMapURL(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldDerpMapURL, v))
}

// AllowlistEnabled applies equality check predicate on the "allowlist_enabled" field. It's identical to AllowlistEnabledEQ.
func AllowlistEnabled(v bool) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldAllowlistEnabled, v))
}

// ExitNodeEnabled applies equality check predicate on the "exit_node_enabled" field. It's identical to ExitNodeEnabledEQ.
func ExitNodeEnabled(v bool) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldExitNodeEnabled, v))
}

// DesiredRunning applies equality check predicate on the "desired_running" field. It's identical to DesiredRunningEQ.
func DesiredRunning(v bool) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldDesiredRunning, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.TailServer {
	return predicate.TailServer(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.TailServer {
	return predicate.TailServer(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldContainsFold(FieldUserID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TailServer {
	return predicate.TailServer(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TailServer {
	return predicate.TailServer(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldContainsFold(FieldName, v))
}

// KeyModeEQ applies the EQ predicate on the "key_mode" field.
func KeyModeEQ(v KeyMode) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldKeyMode, v))
}

// KeyModeNEQ applies the NEQ predicate on the "key_mode" field.
func KeyModeNEQ(v KeyMode) predicate.TailServer {
	return predicate.TailServer(sql.FieldNEQ(FieldKeyMode, v))
}

// KeyModeIn applies the In predicate on the "key_mode" field.
func KeyModeIn(vs ...KeyMode) predicate.TailServer {
	return predicate.TailServer(sql.FieldIn(FieldKeyMode, vs...))
}

// KeyModeNotIn applies the NotIn predicate on the "key_mode" field.
func KeyModeNotIn(vs ...KeyMode) predicate.TailServer {
	return predicate.TailServer(sql.FieldNotIn(FieldKeyMode, vs...))
}

// KeyCipherEQ applies the EQ predicate on the "key_cipher" field.
func KeyCipherEQ(v []byte) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldKeyCipher, v))
}

// KeyCipherNEQ applies the NEQ predicate on the "key_cipher" field.
func KeyCipherNEQ(v []byte) predicate.TailServer {
	return predicate.TailServer(sql.FieldNEQ(FieldKeyCipher, v))
}

// KeyCipherIn applies the In predicate on the "key_cipher" field.
func KeyCipherIn(vs ...[]byte) predicate.TailServer {
	return predicate.TailServer(sql.FieldIn(FieldKeyCipher, vs...))
}

// KeyCipherNotIn applies the NotIn predicate on the "key_cipher" field.
func KeyCipherNotIn(vs ...[]byte) predicate.TailServer {
	return predicate.TailServer(sql.FieldNotIn(FieldKeyCipher, vs...))
}

// KeyCipherGT applies the GT predicate on the "key_cipher" field.
func KeyCipherGT(v []byte) predicate.TailServer {
	return predicate.TailServer(sql.FieldGT(FieldKeyCipher, v))
}

// KeyCipherGTE applies the GTE predicate on the "key_cipher" field.
func KeyCipherGTE(v []byte) predicate.TailServer {
	return predicate.TailServer(sql.FieldGTE(FieldKeyCipher, v))
}

// KeyCipherLT applies the LT predicate on the "key_cipher" field.
func KeyCipherLT(v []byte) predicate.TailServer {
	return predicate.TailServer(sql.FieldLT(FieldKeyCipher, v))
}

// KeyCipherLTE applies the LTE predicate on the "key_cipher" field.
func KeyCipherLTE(v []byte) predicate.TailServer {
	return predicate.TailServer(sql.FieldLTE(FieldKeyCipher, v))
}

// KeyCipherIsNil applies the IsNil predicate on the "key_cipher" field.
func KeyCipherIsNil() predicate.TailServer {
	return predicate.TailServer(sql.FieldIsNull(FieldKeyCipher))
}

// KeyCipherNotNil applies the NotNil predicate on the "key_cipher" field.
func KeyCipherNotNil() predicate.TailServer {
	return predicate.TailServer(sql.FieldNotNull(FieldKeyCipher))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.TailServer {
	return predicate.TailServer(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.TailServer {
	return predicate.TailServer(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldContainsFold(FieldRegion, v))
}

// DerpMapURLEQ applies the EQ predicate on the "derp_map_url" field.
func DerpMapURLEQ(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldDerpMapURL, v))
}

// DerpMapURLNEQ applies the NEQ predicate on the "derp_map_url" field.
func DerpMapURLNEQ(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldNEQ(FieldDerpMapURL, v))
}

// DerpMapURLIn applies the In predicate on the "derp_map_url" field.
func DerpMapURLIn(vs ...string) predicate.TailServer {
	return predicate.TailServer(sql.FieldIn(FieldDerpMapURL, vs...))
}

// DerpMapURLNotIn applies the NotIn predicate on the "derp_map_url" field.
func DerpMapURLNotIn(vs ...string) predicate.TailServer {
	return predicate.TailServer(sql.FieldNotIn(FieldDerpMapURL, vs...))
}

// DerpMapURLGT applies the GT predicate on the "derp_map_url" field.
func DerpMapURLGT(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldGT(FieldDerpMapURL, v))
}

// DerpMapURLGTE applies the GTE predicate on the "derp_map_url" field.
func DerpMapURLGTE(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldGTE(FieldDerpMapURL, v))
}

// DerpMapURLLT applies the LT predicate on the "derp_map_url" field.
func DerpMapURLLT(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldLT(FieldDerpMapURL, v))
}

// DerpMapURLLTE applies the LTE predicate on the "derp_map_url" field.
func DerpMapURLLTE(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldLTE(FieldDerpMapURL, v))
}

// DerpMapURLContains applies the Contains predicate on the "derp_map_url" field.
func DerpMapURLContains(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldContains(FieldDerpMapURL, v))
}

// DerpMapURLHasPrefix applies the HasPrefix predicate on the "derp_map_url" field.
func DerpMapURLHasPrefix(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldHasPrefix(FieldDerpMapURL, v))
}

// DerpMapURLHasSuffix applies the HasSuffix predicate on the "derp_map_url" field.
func DerpMapURLHasSuffix(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldHasSuffix(FieldDerpMapURL, v))
}

// DerpMapURLIsNil applies the IsNil predicate on the "derp_map_url" field.
func DerpMapURLIsNil() predicate.TailServer {
	return predicate.TailServer(sql.FieldIsNull(FieldDerpMapURL))
}

// DerpMapURLNotNil applies the NotNil predicate on the "derp_map_url" field.
func DerpMapURLNotNil() predicate.TailServer {
	return predicate.TailServer(sql.FieldNotNull(FieldDerpMapURL))
}

// DerpMapURLEqualFold applies the EqualFold predicate on the "derp_map_url" field.
func DerpMapURLEqualFold(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldEqualFold(FieldDerpMapURL, v))
}

// DerpMapURLContainsFold applies the ContainsFold predicate on the "derp_map_url" field.
func DerpMapURLContainsFold(v string) predicate.TailServer {
	return predicate.TailServer(sql.FieldContainsFold(FieldDerpMapURL, v))
}

// AllowlistEnabledEQ applies the EQ predicate on the "allowlist_enabled" field.
func AllowlistEnabledEQ(v bool) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldAllowlistEnabled, v))
}

// AllowlistEnabledNEQ applies the NEQ predicate on the "allowlist_enabled" field.
func AllowlistEnabledNEQ(v bool) predicate.TailServer {
	return predicate.TailServer(sql.FieldNEQ(FieldAllowlistEnabled, v))
}

// ExitNodeEnabledEQ applies the EQ predicate on the "exit_node_enabled" field.
func ExitNodeEnabledEQ(v bool) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldExitNodeEnabled, v))
}

// ExitNodeEnabledNEQ applies the NEQ predicate on the "exit_node_enabled" field.
func ExitNodeEnabledNEQ(v bool) predicate.TailServer {
	return predicate.TailServer(sql.FieldNEQ(FieldExitNodeEnabled, v))
}

// DesiredRunningEQ applies the EQ predicate on the "desired_running" field.
func DesiredRunningEQ(v bool) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldDesiredRunning, v))
}

// DesiredRunningNEQ applies the NEQ predicate on the "desired_running" field.
func DesiredRunningNEQ(v bool) predicate.TailServer {
	return predicate.TailServer(sql.FieldNEQ(FieldDesiredRunning, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TailServer {
	return predicate.TailServer(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.TailServer {
	return predicate.TailServer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.TailServer {
	return predicate.TailServer(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMappings applies the HasEdge predicate on the "mappings" edge.
func HasMappings() predicate.TailServer {
	return predicate.TailServer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MappingsTable, MappingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMappingsWith applies the HasEdge predicate on the "mappings" edge with a given conditions (other predicates).
func HasMappingsWith(preds ...predicate.PortMapping) predicate.TailServer {
	return predicate.TailServer(func(s *sql.Selector) {
		step := newMappingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAllowedClients applies the HasEdge predicate on the "allowed_clients" edge.
func HasAllowedClients() predicate.TailServer {
	return predicate.TailServer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AllowedClientsTable, AllowedClientsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAllowedClientsWith applies the HasEdge predicate on the "allowed_clients" edge with a given conditions (other predicates).
func HasAllowedClientsWith(preds ...predicate.AllowedClient) predicate.TailServer {
	return predicate.TailServer(func(s *sql.Selector) {
		step := newAllowedClientsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExitRules applies the HasEdge predicate on the "exit_rules" edge.
func HasExitRules() predicate.TailServer {
	return predicate.TailServer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExitRulesTable, ExitRulesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExitRulesWith applies the HasEdge predicate on the "exit_rules" edge with a given conditions (other predicates).
func HasExitRulesWith(preds ...predicate.ExitRule) predicate.TailServer {
	return predicate.TailServer(func(s *sql.Selector) {
		step := newExitRulesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTransferShares applies the HasEdge predicate on the "transfer_shares" edge.
func HasTransferShares() predicate.TailServer {
	return predicate.TailServer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TransferSharesTable, TransferSharesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransferSharesWith applies the HasEdge predicate on the "transfer_shares" edge with a given conditions (other predicates).
func HasTransferSharesWith(preds ...predicate.TransferShare) predicate.TailServer {
	return predicate.TailServer(func(s *sql.Selector) {
		step := newTransferSharesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TailServer) predicate.TailServer {
	return predicate.TailServer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TailServer) predicate.TailServer {
	return predicate.TailServer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TailServer) predicate.TailServer {
	return predicate.TailServer(sql.NotPredicates(p))
}
