// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIssuer holds the string denoting the issuer field in the database.
	FieldIssuer = "issuer"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// EdgeServers holds the string denoting the servers edge name in mutations.
	EdgeServers = "servers"
	// EdgeExitRules holds the string denoting the exit_rules edge name in mutations.
	EdgeExitRules = "exit_rules"
	// EdgeClients holds the string denoting the clients edge name in mutations.
	EdgeClients = "clients"
	// EdgeDiagnosticRuns holds the string denoting the diagnostic_runs edge name in mutations.
	EdgeDiagnosticRuns = "diagnostic_runs"
	// EdgeRoutes holds the string denoting the routes edge name in mutations.
	EdgeRoutes = "routes"
	// EdgeTransferShares holds the string denoting the transfer_shares edge name in mutations.
	EdgeTransferShares = "transfer_shares"
	// EdgeShareFiles holds the string denoting the share_files edge name in mutations.
	EdgeShareFiles = "share_files"
	// EdgeTransferJobs holds the string denoting the transfer_jobs edge name in mutations.
	EdgeTransferJobs = "transfer_jobs"
	// EdgeTransferItems holds the string denoting the transfer_items edge name in mutations.
	EdgeTransferItems = "transfer_items"
	// EdgeAuditEvents holds the string denoting the audit_events edge name in mutations.
	EdgeAuditEvents = "audit_events"
	// Table holds the table name of the user in the database.
	Table = "users"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "sessions"
	// SessionsInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionsInverseTable = "sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "user_id"
	// ServersTable is the table that holds the servers relation/edge.
	ServersTable = "tail_servers"
	// ServersInverseTable is the table name for the TailServer entity.
	// It exists in this package in order to avoid circular dependency with the "tailserver" package.
	ServersInverseTable = "tail_servers"
	// ServersColumn is the table column denoting the servers relation/edge.
	ServersColumn = "user_id"
	// ExitRulesTable is the table that holds the exit_rules relation/edge.
	ExitRulesTable = "exit_rules"
	// ExitRulesInverseTable is the table name for the ExitRule entity.
	// It exists in this package in order to avoid circular dependency with the "exitrule" package.
	ExitRulesInverseTable = "exit_rules"
	// ExitRulesColumn is the table column denoting the exit_rules relation/edge.
	ExitRulesColumn = "user_id"
	// ClientsTable is the table that holds the clients relation/edge.
	ClientsTable = "tail_clients"
	// ClientsInverseTable is the table name for the TailClient entity.
	// It exists in this package in order to avoid circular dependency with the "tailclient" package.
	ClientsInverseTable = "tail_clients"
	// ClientsColumn is the table column denoting the clients relation/edge.
	ClientsColumn = "user_id"
	// DiagnosticRunsTable is the table that holds the diagnostic_runs relation/edge.
	DiagnosticRunsTable = "diagnostic_runs"
	// DiagnosticRunsInverseTable is the table name for the DiagnosticRun entity.
	// It exists in this package in order to avoid circular dependency with the "diagnosticrun" package.
	DiagnosticRunsInverseTable = "diagnostic_runs"
	// DiagnosticRunsColumn is the table column denoting the diagnostic_runs relation/edge.
	DiagnosticRunsColumn = "user_id"
	// RoutesTable is the table that holds the routes relation/edge.
	RoutesTable = "published_routes"
	// RoutesInverseTable is the table name for the PublishedRoute entity.
	// It exists in this package in order to avoid circular dependency with the "publishedroute" package.
	RoutesInverseTable = "published_routes"
	// RoutesColumn is the table column denoting the routes relation/edge.
	RoutesColumn = "user_id"
	// TransferSharesTable is the table that holds the transfer_shares relation/edge.
	TransferSharesTable = "transfer_shares"
	// TransferSharesInverseTable is the table name for the TransferShare entity.
	// It exists in this package in order to avoid circular dependency with the "transfershare" package.
	TransferSharesInverseTable = "transfer_shares"
	// TransferSharesColumn is the table column denoting the transfer_shares relation/edge.
	TransferSharesColumn = "user_id"
	// ShareFilesTable is the table that holds the share_files relation/edge.
	ShareFilesTable = "share_files"
	// ShareFilesInverseTable is the table name for the ShareFile entity.
	// It exists in this package in order to avoid circular dependency with the "sharefile" package.
	ShareFilesInverseTable = "share_files"
	// ShareFilesColumn is the table column denoting the share_files relation/edge.
	ShareFilesColumn = "user_id"
	// TransferJobsTable is the table that holds the transfer_jobs relation/edge.
	TransferJobsTable = "transfer_jobs"
	// TransferJobsInverseTable is the table name for the TransferJob entity.
	// It exists in this package in order to avoid circular dependency with the "transferjob" package.
	TransferJobsInverseTable = "transfer_jobs"
	// TransferJobsColumn is the table column denoting the transfer_jobs relation/edge.
	TransferJobsColumn = "user_id"
	// TransferItemsTable is the table that holds the transfer_items relation/edge.
	TransferItemsTable = "transfer_items"
	// TransferItemsInverseTable is the table name for the TransferItem entity.
	// It exists in this package in order to avoid circular dependency with the "transferitem" package.
	TransferItemsInverseTable = "transfer_items"
	// TransferItemsColumn is the table column denoting the transfer_items relation/edge.
	TransferItemsColumn = "user_id"
	// AuditEventsTable is the table that holds the audit_events relation/edge.
	AuditEventsTable = "audit_events"
	// AuditEventsInverseTable is the table name for the AuditEvent entity.
	// It exists in this package in order to avoid circular dependency with the "auditevent" package.
	AuditEventsInverseTable = "audit_events"
	// AuditEventsColumn is the table column denoting the audit_events relation/edge.
	AuditEventsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldIssuer,
	FieldSubject,
	FieldEmail,
	FieldDisplayName,
	FieldAvatarURL,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IssuerValidator is a validator for the "issuer" field. It is called by the builders before save.
	IssuerValidator func(string) error
	// SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	SubjectValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIssuer orders the results by the issuer field.
func ByIssuer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuer, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByAvatarURL orders the results by the avatar_url field.
func ByAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarURL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySessionsCount orders the results by sessions count.
func BySessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionsStep(), opts...)
	}
}

// BySessions orders the results by sessions terms.
func BySessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByServersCount orders the results by servers count.
func ByServersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newServersStep(), opts...)
	}
}

// ByServers orders the results by servers terms.
func ByServers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByExitRulesCount orders the results by exit_rules count.
func ByExitRulesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExitRulesStep(), opts...)
	}
}

// ByExitRules orders the results by exit_rules terms.
func ByExitRules(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExitRulesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByClientsCount orders the results by clients count.
func ByClientsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newClientsStep(), opts...)
	}
}

// ByClients orders the results by clients terms.
func ByClients(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClientsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDiagnosticRunsCount orders the results by diagnostic_runs count.
func ByDiagnosticRunsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDiagnosticRunsStep(), opts...)
	}
}

// ByDiagnosticRuns orders the results by diagnostic_runs terms.
func ByDiagnosticRuns(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDiagnosticRunsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRoutesCount orders the results by routes count.
func ByRoutesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRoutesStep(), opts...)
	}
}

// ByRoutes orders the results by routes terms.
func ByRoutes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoutesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTransferSharesCount orders the results by transfer_shares count.
func ByTransferSharesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTransferSharesStep(), opts...)
	}
}

// ByTransferShares orders the results by transfer_shares terms.
func ByTransferShares(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTransferSharesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByShareFilesCount orders the results by share_files count.
func ByShareFilesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newShareFilesStep(), opts...)
	}
}

// ByShareFiles orders the results by share_files terms.
func ByShareFiles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newShareFilesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTransferJobsCount orders the results by transfer_jobs count.
func ByTransferJobsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTransferJobsStep(), opts...)
	}
}

// ByTransferJobs orders the results by transfer_jobs terms.
func ByTransferJobs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTransferJobsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTransferItemsCount orders the results by transfer_items count.
func ByTransferItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTransferItemsStep(), opts...)
	}
}

// ByTransferItems orders the results by transfer_items terms.
func ByTransferItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTransferItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAuditEventsCount orders the results by audit_events count.
func ByAuditEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuditEventsStep(), opts...)
	}
}

// ByAuditEvents orders the results by audit_events terms.
func ByAuditEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuditEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
	)
}
func newServersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ServersTable, ServersColumn),
	)
}
func newExitRulesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExitRulesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ExitRulesTable, ExitRulesColumn),
	)
}
func newClientsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClientsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ClientsTable, ClientsColumn),
	)
}
func newDiagnosticRunsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DiagnosticRunsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DiagnosticRunsTable, DiagnosticRunsColumn),
	)
}
func newRoutesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoutesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RoutesTable, RoutesColumn),
	)
}
func newTransferSharesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TransferSharesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TransferSharesTable, TransferSharesColumn),
	)
}
func newShareFilesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ShareFilesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ShareFilesTable, ShareFilesColumn),
	)
}
func newTransferJobsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TransferJobsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TransferJobsTable, TransferJobsColumn),
	)
}
func newTransferItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TransferItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TransferItemsTable, TransferItemsColumn),
	)
}
func newAuditEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuditEventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AuditEventsTable, AuditEventsColumn),
	)
}
