// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AllowedClient is the predicate function for allowedclient builders.
type AllowedClient func(*sql.Selector)

// AuditEvent is the predicate function for auditevent builders.
type AuditEvent func(*sql.Selector)

// ExitRule is the predicate function for exitrule builders.
type ExitRule func(*sql.Selector)

// LoginFlow is the predicate function for loginflow builders.
type LoginFlow func(*sql.Selector)

// PortMapping is the predicate function for portmapping builders.
type PortMapping func(*sql.Selector)

// PublishedRoute is the predicate function for publishedroute builders.
type PublishedRoute func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// TailClient is the predicate function for tailclient builders.
type TailClient func(*sql.Selector)

// TailServer is the predicate function for tailserver builders.
type TailServer func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
